# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/sidejob/ethernet_NN/kitsum_1024B_xy_20231211/kits_prj.srcs/sources_1/ip/fifo_loopback_100g/fifo_loopback_100g.xci
# IP: The module: 'fifo_loopback_100g' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/sidejob/ethernet_NN/kitsum_1024B_xy_20231211/kits_prj.srcs/sources_1/ip/fifo_loopback_100g/fifo_loopback_100g.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_loopback_100g'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/sidejob/ethernet_NN/kitsum_1024B_xy_20231211/kits_prj.srcs/sources_1/ip/fifo_loopback_100g/fifo_loopback_100g_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_loopback_100g'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/sidejob/ethernet_NN/kitsum_1024B_xy_20231211/kits_prj.srcs/sources_1/ip/fifo_loopback_100g/fifo_loopback_100g_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_loopback_100g'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: d:/sidejob/ethernet_NN/kitsum_1024B_xy_20231211/kits_prj.srcs/sources_1/ip/fifo_loopback_100g/fifo_loopback_100g.xci
# IP: The module: 'fifo_loopback_100g' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/sidejob/ethernet_NN/kitsum_1024B_xy_20231211/kits_prj.srcs/sources_1/ip/fifo_loopback_100g/fifo_loopback_100g.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_loopback_100g'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/sidejob/ethernet_NN/kitsum_1024B_xy_20231211/kits_prj.srcs/sources_1/ip/fifo_loopback_100g/fifo_loopback_100g_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_loopback_100g'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/sidejob/ethernet_NN/kitsum_1024B_xy_20231211/kits_prj.srcs/sources_1/ip/fifo_loopback_100g/fifo_loopback_100g_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_loopback_100g'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
