# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/sidejob/kitsum_1024B_xy_20231211/kits_prj.srcs/sources_1/ip/fifo_loopback/fifo_loopback.xci
# IP: The module: 'fifo_loopback' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/sidejob/kitsum_1024B_xy_20231211/kits_prj.srcs/sources_1/ip/fifo_loopback/fifo_loopback.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_loopback'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/sidejob/kitsum_1024B_xy_20231211/kits_prj.srcs/sources_1/ip/fifo_loopback/fifo_loopback_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_loopback'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/sidejob/kitsum_1024B_xy_20231211/kits_prj.srcs/sources_1/ip/fifo_loopback/fifo_loopback_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_loopback'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: D:/sidejob/kitsum_1024B_xy_20231211/kits_prj.srcs/sources_1/ip/fifo_loopback/fifo_loopback.xci
# IP: The module: 'fifo_loopback' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/sidejob/kitsum_1024B_xy_20231211/kits_prj.srcs/sources_1/ip/fifo_loopback/fifo_loopback.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_loopback'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/sidejob/kitsum_1024B_xy_20231211/kits_prj.srcs/sources_1/ip/fifo_loopback/fifo_loopback_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_loopback'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/sidejob/kitsum_1024B_xy_20231211/kits_prj.srcs/sources_1/ip/fifo_loopback/fifo_loopback_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_loopback'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
