# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/kits_top.xdc

# IP: ip/cmac_usplus_3/cmac_usplus_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cmac_usplus_3 || ORIG_REF_NAME==cmac_usplus_3} -quiet] -quiet

# IP: ip/cmac_usplus_3/ip_0/cmac_usplus_3_gt.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cmac_usplus_3_gt || ORIG_REF_NAME==cmac_usplus_3_gt} -quiet] -quiet

# IP: ip/cmac_usplus_2/cmac_usplus_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cmac_usplus_2 || ORIG_REF_NAME==cmac_usplus_2} -quiet] -quiet

# IP: ip/cmac_usplus_2/ip_0/cmac_usplus_2_gt.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cmac_usplus_2_gt || ORIG_REF_NAME==cmac_usplus_2_gt} -quiet] -quiet

# IP: ip/cmac_usplus_1/cmac_usplus_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cmac_usplus_1 || ORIG_REF_NAME==cmac_usplus_1} -quiet] -quiet

# IP: ip/cmac_usplus_1/ip_0/cmac_usplus_1_gt.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cmac_usplus_1_gt || ORIG_REF_NAME==cmac_usplus_1_gt} -quiet] -quiet

# IP: IP/DUT_OUT/DUT_OUT.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DUT_OUT || ORIG_REF_NAME==DUT_OUT} -quiet] -quiet

# IP: IP/DUT_OUT/ip_3/DUT_OUT_gt_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DUT_OUT_gt_3 || ORIG_REF_NAME==DUT_OUT_gt_3} -quiet] -quiet

# IP: IP/DUT_OUT/ip_2/DUT_OUT_gt_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DUT_OUT_gt_2 || ORIG_REF_NAME==DUT_OUT_gt_2} -quiet] -quiet

# IP: IP/DUT_OUT/ip_1/DUT_OUT_gt_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DUT_OUT_gt_1 || ORIG_REF_NAME==DUT_OUT_gt_1} -quiet] -quiet

# IP: IP/DUT_OUT/ip_0/DUT_OUT_gt.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DUT_OUT_gt || ORIG_REF_NAME==DUT_OUT_gt} -quiet] -quiet

# XDC: ip/cmac_usplus_3/ip_0/synth/cmac_usplus_3_gt_ooc.xdc

# XDC: ip/cmac_usplus_3/ip_0/synth/cmac_usplus_3_gt.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==cmac_usplus_3_gt || ORIG_REF_NAME==cmac_usplus_3_gt} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: ip/cmac_usplus_3/synth/cmac_usplus_3_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==cmac_usplus_3 || ORIG_REF_NAME==cmac_usplus_3} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: ip/cmac_usplus_3/synth/cmac_usplus_3.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==cmac_usplus_3 || ORIG_REF_NAME==cmac_usplus_3} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: ip/cmac_usplus_3/synth/cmac_usplus_3_ooc.xdc

# XDC: ip/cmac_usplus_2/ip_0/synth/cmac_usplus_2_gt_ooc.xdc

# XDC: ip/cmac_usplus_2/ip_0/synth/cmac_usplus_2_gt.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==cmac_usplus_2_gt || ORIG_REF_NAME==cmac_usplus_2_gt} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: ip/cmac_usplus_2/synth/cmac_usplus_2_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==cmac_usplus_2 || ORIG_REF_NAME==cmac_usplus_2} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: ip/cmac_usplus_2/synth/cmac_usplus_2.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==cmac_usplus_2 || ORIG_REF_NAME==cmac_usplus_2} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: ip/cmac_usplus_2/synth/cmac_usplus_2_ooc.xdc

# XDC: ip/cmac_usplus_1/ip_0/synth/cmac_usplus_1_gt_ooc.xdc

# XDC: ip/cmac_usplus_1/ip_0/synth/cmac_usplus_1_gt.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==cmac_usplus_1_gt || ORIG_REF_NAME==cmac_usplus_1_gt} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: ip/cmac_usplus_1/synth/cmac_usplus_1_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==cmac_usplus_1 || ORIG_REF_NAME==cmac_usplus_1} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: ip/cmac_usplus_1/synth/cmac_usplus_1.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==cmac_usplus_1 || ORIG_REF_NAME==cmac_usplus_1} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: ip/cmac_usplus_1/synth/cmac_usplus_1_ooc.xdc

# XDC: IP/DUT_OUT/ip_3/synth/DUT_OUT_gt_3_ooc.xdc

# XDC: IP/DUT_OUT/ip_3/synth/DUT_OUT_gt_3.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==DUT_OUT_gt_3 || ORIG_REF_NAME==DUT_OUT_gt_3} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: IP/DUT_OUT/ip_2/synth/DUT_OUT_gt_2_ooc.xdc

# XDC: IP/DUT_OUT/ip_2/synth/DUT_OUT_gt_2.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==DUT_OUT_gt_2 || ORIG_REF_NAME==DUT_OUT_gt_2} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: IP/DUT_OUT/ip_1/synth/DUT_OUT_gt_1_ooc.xdc

# XDC: IP/DUT_OUT/ip_1/synth/DUT_OUT_gt_1.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==DUT_OUT_gt_1 || ORIG_REF_NAME==DUT_OUT_gt_1} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: IP/DUT_OUT/ip_0/synth/DUT_OUT_gt_ooc.xdc

# XDC: IP/DUT_OUT/ip_0/synth/DUT_OUT_gt.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==DUT_OUT_gt || ORIG_REF_NAME==DUT_OUT_gt} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: IP/DUT_OUT/synth/DUT_OUT_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==DUT_OUT || ORIG_REF_NAME==DUT_OUT} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: IP/DUT_OUT/synth/DUT_OUT.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==DUT_OUT || ORIG_REF_NAME==DUT_OUT} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: IP/DUT_OUT/synth/DUT_OUT_ooc.xdc
