# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "D:/sidejob/ethernet_NN/kitsum_1024B_xy_20231211/kits_prj.runs/synth_1/kits_top.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

OPTRACE "synth_1" START { ROLLUP_AUTO }
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xczu19eg-ffvc1760-2-i

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/sidejob/ethernet_NN/kitsum_1024B_xy_20231211/kits_prj.cache/wt [current_project]
set_property parent.project_path D:/sidejob/ethernet_NN/kitsum_1024B_xy_20231211/kits_prj.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths d:/sidejob/ethernet_NN/NN/hls_component/hls_component/hls/impl/ip [current_project]
update_ip_catalog
set_property ip_output_repo d:/sidejob/ethernet_NN/kitsum_1024B_xy_20231211/kits_prj.cache/ip [current_project]
set_property ip_cache_permissions disable [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_verilog -library xil_defaultlib {
  D:/sidejob/ethernet_NN/kitsum_1024B_xy_20231211/kits_prj.srcs/sources_1/new/Ether100G_bank129.v
  D:/sidejob/ethernet_NN/kitsum_1024B_xy_20231211/kits_prj.srcs/sources_1/new/Ether100G_bank130.v
  D:/sidejob/ethernet_NN/kitsum_1024B_xy_20231211/kits_prj.srcs/sources_1/new/Ether100G_bank131.v
  D:/sidejob/ethernet_NN/kitsum_1024B_xy_20231211/kits_prj.srcs/sources_1/imports/imports/cmac_usplus_0_axis_pkt_gen.v
  D:/sidejob/ethernet_NN/kitsum_1024B_xy_20231211/kits_prj.srcs/sources_1/imports/imports/cmac_usplus_0_axis_pkt_mon.v
  D:/sidejob/ethernet_NN/kitsum_1024B_xy_20231211/kits_prj.srcs/sources_1/imports/imports/cmac_usplus_0_pkt_gen_mon.v
  D:/sidejob/ethernet_NN/kitsum_1024B_xy_20231211/kits_prj.srcs/sources_1/new/cmac_usplus_1_exdes.v
  D:/sidejob/ethernet_NN/kitsum_1024B_xy_20231211/kits_prj.srcs/sources_1/new/cmac_usplus_2_exdes.v
  D:/sidejob/ethernet_NN/kitsum_1024B_xy_20231211/kits_prj.srcs/sources_1/new/cmac_usplus_3_exdes.v
  D:/sidejob/ethernet_NN/kitsum_1024B_xy_20231211/kits_prj.srcs/sources_1/new/kits_top.v
}
read_ip -quiet D:/sidejob/ethernet_NN/kitsum_1024B_xy_20231211/kits_prj.srcs/sources_1/ip/cmac_usplus_3/cmac_usplus_3.xci
set_property used_in_implementation false [get_files -all d:/sidejob/ethernet_NN/kitsum_1024B_xy_20231211/kits_prj.srcs/sources_1/ip/cmac_usplus_3/ip_0/synth/cmac_usplus_3_gt_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/sidejob/ethernet_NN/kitsum_1024B_xy_20231211/kits_prj.srcs/sources_1/ip/cmac_usplus_3/ip_0/synth/cmac_usplus_3_gt.xdc]
set_property used_in_implementation false [get_files -all d:/sidejob/ethernet_NN/kitsum_1024B_xy_20231211/kits_prj.srcs/sources_1/ip/cmac_usplus_3/synth/cmac_usplus_3_board.xdc]
set_property used_in_implementation false [get_files -all d:/sidejob/ethernet_NN/kitsum_1024B_xy_20231211/kits_prj.srcs/sources_1/ip/cmac_usplus_3/synth/cmac_usplus_3.xdc]
set_property used_in_implementation false [get_files -all d:/sidejob/ethernet_NN/kitsum_1024B_xy_20231211/kits_prj.srcs/sources_1/ip/cmac_usplus_3/synth/cmac_usplus_3_ooc.xdc]

read_ip -quiet D:/sidejob/ethernet_NN/kitsum_1024B_xy_20231211/kits_prj.srcs/sources_1/ip/cmac_usplus_2/cmac_usplus_2.xci
set_property used_in_implementation false [get_files -all d:/sidejob/ethernet_NN/kitsum_1024B_xy_20231211/kits_prj.srcs/sources_1/ip/cmac_usplus_2/ip_0/synth/cmac_usplus_2_gt_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/sidejob/ethernet_NN/kitsum_1024B_xy_20231211/kits_prj.srcs/sources_1/ip/cmac_usplus_2/ip_0/synth/cmac_usplus_2_gt.xdc]
set_property used_in_implementation false [get_files -all d:/sidejob/ethernet_NN/kitsum_1024B_xy_20231211/kits_prj.srcs/sources_1/ip/cmac_usplus_2/synth/cmac_usplus_2_board.xdc]
set_property used_in_implementation false [get_files -all d:/sidejob/ethernet_NN/kitsum_1024B_xy_20231211/kits_prj.srcs/sources_1/ip/cmac_usplus_2/synth/cmac_usplus_2.xdc]
set_property used_in_implementation false [get_files -all d:/sidejob/ethernet_NN/kitsum_1024B_xy_20231211/kits_prj.srcs/sources_1/ip/cmac_usplus_2/synth/cmac_usplus_2_ooc.xdc]

read_ip -quiet D:/sidejob/ethernet_NN/kitsum_1024B_xy_20231211/kits_prj.srcs/sources_1/ip/cmac_usplus_1/cmac_usplus_1.xci
set_property used_in_implementation false [get_files -all d:/sidejob/ethernet_NN/kitsum_1024B_xy_20231211/kits_prj.srcs/sources_1/ip/cmac_usplus_1/ip_0/synth/cmac_usplus_1_gt_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/sidejob/ethernet_NN/kitsum_1024B_xy_20231211/kits_prj.srcs/sources_1/ip/cmac_usplus_1/ip_0/synth/cmac_usplus_1_gt.xdc]
set_property used_in_implementation false [get_files -all d:/sidejob/ethernet_NN/kitsum_1024B_xy_20231211/kits_prj.srcs/sources_1/ip/cmac_usplus_1/synth/cmac_usplus_1_board.xdc]
set_property used_in_implementation false [get_files -all d:/sidejob/ethernet_NN/kitsum_1024B_xy_20231211/kits_prj.srcs/sources_1/ip/cmac_usplus_1/synth/cmac_usplus_1.xdc]
set_property used_in_implementation false [get_files -all d:/sidejob/ethernet_NN/kitsum_1024B_xy_20231211/kits_prj.srcs/sources_1/ip/cmac_usplus_1/synth/cmac_usplus_1_ooc.xdc]

read_ip -quiet D:/sidejob/ethernet_NN/kitsum_1024B_xy_20231211/kits_prj.srcs/sources_1/IP/DUT_OUT/DUT_OUT.xci
set_property used_in_implementation false [get_files -all d:/sidejob/ethernet_NN/kitsum_1024B_xy_20231211/kits_prj.srcs/sources_1/IP/DUT_OUT/ip_3/synth/DUT_OUT_gt_3_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/sidejob/ethernet_NN/kitsum_1024B_xy_20231211/kits_prj.srcs/sources_1/IP/DUT_OUT/ip_3/synth/DUT_OUT_gt_3.xdc]
set_property used_in_implementation false [get_files -all d:/sidejob/ethernet_NN/kitsum_1024B_xy_20231211/kits_prj.srcs/sources_1/IP/DUT_OUT/ip_2/synth/DUT_OUT_gt_2_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/sidejob/ethernet_NN/kitsum_1024B_xy_20231211/kits_prj.srcs/sources_1/IP/DUT_OUT/ip_2/synth/DUT_OUT_gt_2.xdc]
set_property used_in_implementation false [get_files -all d:/sidejob/ethernet_NN/kitsum_1024B_xy_20231211/kits_prj.srcs/sources_1/IP/DUT_OUT/ip_1/synth/DUT_OUT_gt_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/sidejob/ethernet_NN/kitsum_1024B_xy_20231211/kits_prj.srcs/sources_1/IP/DUT_OUT/ip_1/synth/DUT_OUT_gt_1.xdc]
set_property used_in_implementation false [get_files -all d:/sidejob/ethernet_NN/kitsum_1024B_xy_20231211/kits_prj.srcs/sources_1/IP/DUT_OUT/ip_0/synth/DUT_OUT_gt_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/sidejob/ethernet_NN/kitsum_1024B_xy_20231211/kits_prj.srcs/sources_1/IP/DUT_OUT/ip_0/synth/DUT_OUT_gt.xdc]
set_property used_in_implementation false [get_files -all d:/sidejob/ethernet_NN/kitsum_1024B_xy_20231211/kits_prj.srcs/sources_1/IP/DUT_OUT/synth/DUT_OUT_board.xdc]
set_property used_in_implementation false [get_files -all d:/sidejob/ethernet_NN/kitsum_1024B_xy_20231211/kits_prj.srcs/sources_1/IP/DUT_OUT/synth/DUT_OUT.xdc]
set_property used_in_implementation false [get_files -all d:/sidejob/ethernet_NN/kitsum_1024B_xy_20231211/kits_prj.srcs/sources_1/IP/DUT_OUT/synth/DUT_OUT_ooc.xdc]

read_ip -quiet D:/sidejob/ethernet_NN/kitsum_1024B_xy_20231211/kits_prj.srcs/sources_1/IP/vio_rst/vio_rst.xci
set_property used_in_implementation false [get_files -all d:/sidejob/ethernet_NN/kitsum_1024B_xy_20231211/kits_prj.srcs/sources_1/IP/vio_rst/vio_rst.xdc]
set_property used_in_implementation false [get_files -all d:/sidejob/ethernet_NN/kitsum_1024B_xy_20231211/kits_prj.srcs/sources_1/IP/vio_rst/vio_rst_ooc.xdc]

read_ip -quiet D:/sidejob/ethernet_NN/kitsum_1024B_xy_20231211/kits_prj.srcs/sources_1/ip/fifo_loopback_100g/fifo_loopback_100g.xci
set_property used_in_implementation false [get_files -all d:/sidejob/ethernet_NN/kitsum_1024B_xy_20231211/kits_prj.srcs/sources_1/ip/fifo_loopback_100g/fifo_loopback_100g.xdc]
set_property used_in_implementation false [get_files -all d:/sidejob/ethernet_NN/kitsum_1024B_xy_20231211/kits_prj.srcs/sources_1/ip/fifo_loopback_100g/fifo_loopback_100g_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/sidejob/ethernet_NN/kitsum_1024B_xy_20231211/kits_prj.srcs/sources_1/ip/fifo_loopback_100g/fifo_loopback_100g_ooc.xdc]

read_ip -quiet d:/sidejob/ethernet_NN/kitsum_1024B_xy_20231211/kits_prj.srcs/sources_1/ip/CNN_stream_0/CNN_stream_0.xci
set_property used_in_implementation false [get_files -all d:/sidejob/ethernet_NN/kitsum_1024B_xy_20231211/kits_prj.srcs/sources_1/ip/CNN_stream_0/constraints/CNN_stream_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/sidejob/ethernet_NN/kitsum_1024B_xy_20231211/kits_prj.srcs/constrs_1/new/kits_top.xdc
set_property used_in_implementation false [get_files D:/sidejob/ethernet_NN/kitsum_1024B_xy_20231211/kits_prj.srcs/constrs_1/new/kits_top.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top kits_top -part xczu19eg-ffvc1760-2-i
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef kits_top.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
generate_parallel_reports -reports { "report_utilization -file kits_top_utilization_synth.rpt -pb kits_top_utilization_synth.pb"  } 
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
