// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module CNN_stream_feature_separate_layer_stream_9u_s (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        din_TDATA,
        din_TVALID,
        din_TREADY,
        len_x_0_din,
        len_x_0_full_n,
        len_x_0_write,
        len_x_0_num_data_valid,
        len_x_0_fifo_cap,
        len_x_1_din,
        len_x_1_full_n,
        len_x_1_write,
        len_x_1_num_data_valid,
        len_x_1_fifo_cap,
        len_x_2_din,
        len_x_2_full_n,
        len_x_2_write,
        len_x_2_num_data_valid,
        len_x_2_fifo_cap,
        len_x_3_din,
        len_x_3_full_n,
        len_x_3_write,
        len_x_3_num_data_valid,
        len_x_3_fifo_cap,
        len_x_4_din,
        len_x_4_full_n,
        len_x_4_write,
        len_x_4_num_data_valid,
        len_x_4_fifo_cap,
        len_x_5_din,
        len_x_5_full_n,
        len_x_5_write,
        len_x_5_num_data_valid,
        len_x_5_fifo_cap,
        len_x_6_din,
        len_x_6_full_n,
        len_x_6_write,
        len_x_6_num_data_valid,
        len_x_6_fifo_cap,
        len_x_7_din,
        len_x_7_full_n,
        len_x_7_write,
        len_x_7_num_data_valid,
        len_x_7_fifo_cap,
        len_x_8_din,
        len_x_8_full_n,
        len_x_8_write,
        len_x_8_num_data_valid,
        len_x_8_fifo_cap,
        ipd_x_0_din,
        ipd_x_0_full_n,
        ipd_x_0_write,
        ipd_x_0_num_data_valid,
        ipd_x_0_fifo_cap,
        ipd_x_1_din,
        ipd_x_1_full_n,
        ipd_x_1_write,
        ipd_x_1_num_data_valid,
        ipd_x_1_fifo_cap,
        ipd_x_2_din,
        ipd_x_2_full_n,
        ipd_x_2_write,
        ipd_x_2_num_data_valid,
        ipd_x_2_fifo_cap,
        ipd_x_3_din,
        ipd_x_3_full_n,
        ipd_x_3_write,
        ipd_x_3_num_data_valid,
        ipd_x_3_fifo_cap,
        ipd_x_4_din,
        ipd_x_4_full_n,
        ipd_x_4_write,
        ipd_x_4_num_data_valid,
        ipd_x_4_fifo_cap,
        ipd_x_5_din,
        ipd_x_5_full_n,
        ipd_x_5_write,
        ipd_x_5_num_data_valid,
        ipd_x_5_fifo_cap,
        ipd_x_6_din,
        ipd_x_6_full_n,
        ipd_x_6_write,
        ipd_x_6_num_data_valid,
        ipd_x_6_fifo_cap,
        ipd_x_7_din,
        ipd_x_7_full_n,
        ipd_x_7_write,
        ipd_x_7_num_data_valid,
        ipd_x_7_fifo_cap,
        ipd_x_8_din,
        ipd_x_8_full_n,
        ipd_x_8_write,
        ipd_x_8_num_data_valid,
        ipd_x_8_fifo_cap
);

parameter    ap_ST_fsm_state1 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [143:0] din_TDATA;
input   din_TVALID;
output   din_TREADY;
output  [7:0] len_x_0_din;
input   len_x_0_full_n;
output   len_x_0_write;
input  [2:0] len_x_0_num_data_valid;
input  [2:0] len_x_0_fifo_cap;
output  [7:0] len_x_1_din;
input   len_x_1_full_n;
output   len_x_1_write;
input  [2:0] len_x_1_num_data_valid;
input  [2:0] len_x_1_fifo_cap;
output  [7:0] len_x_2_din;
input   len_x_2_full_n;
output   len_x_2_write;
input  [2:0] len_x_2_num_data_valid;
input  [2:0] len_x_2_fifo_cap;
output  [7:0] len_x_3_din;
input   len_x_3_full_n;
output   len_x_3_write;
input  [2:0] len_x_3_num_data_valid;
input  [2:0] len_x_3_fifo_cap;
output  [7:0] len_x_4_din;
input   len_x_4_full_n;
output   len_x_4_write;
input  [2:0] len_x_4_num_data_valid;
input  [2:0] len_x_4_fifo_cap;
output  [7:0] len_x_5_din;
input   len_x_5_full_n;
output   len_x_5_write;
input  [2:0] len_x_5_num_data_valid;
input  [2:0] len_x_5_fifo_cap;
output  [7:0] len_x_6_din;
input   len_x_6_full_n;
output   len_x_6_write;
input  [2:0] len_x_6_num_data_valid;
input  [2:0] len_x_6_fifo_cap;
output  [7:0] len_x_7_din;
input   len_x_7_full_n;
output   len_x_7_write;
input  [2:0] len_x_7_num_data_valid;
input  [2:0] len_x_7_fifo_cap;
output  [7:0] len_x_8_din;
input   len_x_8_full_n;
output   len_x_8_write;
input  [2:0] len_x_8_num_data_valid;
input  [2:0] len_x_8_fifo_cap;
output  [7:0] ipd_x_0_din;
input   ipd_x_0_full_n;
output   ipd_x_0_write;
input  [2:0] ipd_x_0_num_data_valid;
input  [2:0] ipd_x_0_fifo_cap;
output  [7:0] ipd_x_1_din;
input   ipd_x_1_full_n;
output   ipd_x_1_write;
input  [2:0] ipd_x_1_num_data_valid;
input  [2:0] ipd_x_1_fifo_cap;
output  [7:0] ipd_x_2_din;
input   ipd_x_2_full_n;
output   ipd_x_2_write;
input  [2:0] ipd_x_2_num_data_valid;
input  [2:0] ipd_x_2_fifo_cap;
output  [7:0] ipd_x_3_din;
input   ipd_x_3_full_n;
output   ipd_x_3_write;
input  [2:0] ipd_x_3_num_data_valid;
input  [2:0] ipd_x_3_fifo_cap;
output  [7:0] ipd_x_4_din;
input   ipd_x_4_full_n;
output   ipd_x_4_write;
input  [2:0] ipd_x_4_num_data_valid;
input  [2:0] ipd_x_4_fifo_cap;
output  [7:0] ipd_x_5_din;
input   ipd_x_5_full_n;
output   ipd_x_5_write;
input  [2:0] ipd_x_5_num_data_valid;
input  [2:0] ipd_x_5_fifo_cap;
output  [7:0] ipd_x_6_din;
input   ipd_x_6_full_n;
output   ipd_x_6_write;
input  [2:0] ipd_x_6_num_data_valid;
input  [2:0] ipd_x_6_fifo_cap;
output  [7:0] ipd_x_7_din;
input   ipd_x_7_full_n;
output   ipd_x_7_write;
input  [2:0] ipd_x_7_num_data_valid;
input  [2:0] ipd_x_7_fifo_cap;
output  [7:0] ipd_x_8_din;
input   ipd_x_8_full_n;
output   ipd_x_8_write;
input  [2:0] ipd_x_8_num_data_valid;
input  [2:0] ipd_x_8_fifo_cap;

reg ap_done;
reg ap_idle;
reg start_write;
reg len_x_0_write;
reg len_x_1_write;
reg len_x_2_write;
reg len_x_3_write;
reg len_x_4_write;
reg len_x_5_write;
reg len_x_6_write;
reg len_x_7_write;
reg len_x_8_write;
reg ipd_x_0_write;
reg ipd_x_1_write;
reg ipd_x_2_write;
reg ipd_x_3_write;
reg ipd_x_4_write;
reg ipd_x_5_write;
reg ipd_x_6_write;
reg ipd_x_7_write;
reg ipd_x_8_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg    din_TDATA_blk_n;
reg    len_x_0_blk_n;
reg    len_x_1_blk_n;
reg    len_x_2_blk_n;
reg    len_x_3_blk_n;
reg    len_x_4_blk_n;
reg    len_x_5_blk_n;
reg    len_x_6_blk_n;
reg    len_x_7_blk_n;
reg    len_x_8_blk_n;
reg    ipd_x_0_blk_n;
reg    ipd_x_1_blk_n;
reg    ipd_x_2_blk_n;
reg    ipd_x_3_blk_n;
reg    ipd_x_4_blk_n;
reg    ipd_x_5_blk_n;
reg    ipd_x_6_blk_n;
reg    ipd_x_7_blk_n;
reg    ipd_x_8_blk_n;
reg    ap_block_state1;
reg   [0:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    regslice_both_din_U_apdone_blk;
wire   [143:0] din_TDATA_int_regslice;
wire    din_TVALID_int_regslice;
reg    din_TREADY_int_regslice;
wire    regslice_both_din_U_ack_in;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 1'd1;
end

CNN_stream_regslice_both #(
    .DataWidth( 144 ))
regslice_both_din_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(din_TDATA),
    .vld_in(din_TVALID),
    .ack_in(regslice_both_din_U_ack_in),
    .data_out(din_TDATA_int_regslice),
    .vld_out(din_TVALID_int_regslice),
    .ack_out(din_TREADY_int_regslice),
    .apdone_blk(regslice_both_din_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((real_start == 1'b1) & (internal_ap_ready == 1'b0))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((real_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        din_TDATA_blk_n = din_TVALID_int_regslice;
    end else begin
        din_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        din_TREADY_int_regslice = 1'b1;
    end else begin
        din_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ipd_x_0_blk_n = ipd_x_0_full_n;
    end else begin
        ipd_x_0_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        ipd_x_0_write = 1'b1;
    end else begin
        ipd_x_0_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ipd_x_1_blk_n = ipd_x_1_full_n;
    end else begin
        ipd_x_1_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        ipd_x_1_write = 1'b1;
    end else begin
        ipd_x_1_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ipd_x_2_blk_n = ipd_x_2_full_n;
    end else begin
        ipd_x_2_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        ipd_x_2_write = 1'b1;
    end else begin
        ipd_x_2_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ipd_x_3_blk_n = ipd_x_3_full_n;
    end else begin
        ipd_x_3_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        ipd_x_3_write = 1'b1;
    end else begin
        ipd_x_3_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ipd_x_4_blk_n = ipd_x_4_full_n;
    end else begin
        ipd_x_4_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        ipd_x_4_write = 1'b1;
    end else begin
        ipd_x_4_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ipd_x_5_blk_n = ipd_x_5_full_n;
    end else begin
        ipd_x_5_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        ipd_x_5_write = 1'b1;
    end else begin
        ipd_x_5_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ipd_x_6_blk_n = ipd_x_6_full_n;
    end else begin
        ipd_x_6_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        ipd_x_6_write = 1'b1;
    end else begin
        ipd_x_6_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ipd_x_7_blk_n = ipd_x_7_full_n;
    end else begin
        ipd_x_7_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        ipd_x_7_write = 1'b1;
    end else begin
        ipd_x_7_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ipd_x_8_blk_n = ipd_x_8_full_n;
    end else begin
        ipd_x_8_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        ipd_x_8_write = 1'b1;
    end else begin
        ipd_x_8_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        len_x_0_blk_n = len_x_0_full_n;
    end else begin
        len_x_0_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        len_x_0_write = 1'b1;
    end else begin
        len_x_0_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        len_x_1_blk_n = len_x_1_full_n;
    end else begin
        len_x_1_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        len_x_1_write = 1'b1;
    end else begin
        len_x_1_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        len_x_2_blk_n = len_x_2_full_n;
    end else begin
        len_x_2_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        len_x_2_write = 1'b1;
    end else begin
        len_x_2_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        len_x_3_blk_n = len_x_3_full_n;
    end else begin
        len_x_3_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        len_x_3_write = 1'b1;
    end else begin
        len_x_3_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        len_x_4_blk_n = len_x_4_full_n;
    end else begin
        len_x_4_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        len_x_4_write = 1'b1;
    end else begin
        len_x_4_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        len_x_5_blk_n = len_x_5_full_n;
    end else begin
        len_x_5_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        len_x_5_write = 1'b1;
    end else begin
        len_x_5_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        len_x_6_blk_n = len_x_6_full_n;
    end else begin
        len_x_6_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        len_x_6_write = 1'b1;
    end else begin
        len_x_6_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        len_x_7_blk_n = len_x_7_full_n;
    end else begin
        len_x_7_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        len_x_7_write = 1'b1;
    end else begin
        len_x_7_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        len_x_8_blk_n = len_x_8_full_n;
    end else begin
        len_x_8_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        len_x_8_write = 1'b1;
    end else begin
        len_x_8_write = 1'b0;
    end
end

always @ (*) begin
    if (((start_full_n == 1'b0) & (start_once_reg == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((real_start == 1'b1) & (start_once_reg == 1'b0))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_state1 = ((ipd_x_0_full_n == 1'b0) | (len_x_8_full_n == 1'b0) | (len_x_7_full_n == 1'b0) | (real_start == 1'b0) | (len_x_6_full_n == 1'b0) | (len_x_5_full_n == 1'b0) | (len_x_4_full_n == 1'b0) | (len_x_3_full_n == 1'b0) | (len_x_2_full_n == 1'b0) | (len_x_1_full_n == 1'b0) | (len_x_0_full_n == 1'b0) | (din_TVALID_int_regslice == 1'b0) | (ap_done_reg == 1'b1) | (ipd_x_8_full_n == 1'b0) | (ipd_x_7_full_n == 1'b0) | (ipd_x_6_full_n == 1'b0) | (ipd_x_5_full_n == 1'b0) | (ipd_x_4_full_n == 1'b0) | (ipd_x_3_full_n == 1'b0) | (ipd_x_2_full_n == 1'b0) | (ipd_x_1_full_n == 1'b0));
end

assign ap_ready = internal_ap_ready;

assign din_TREADY = regslice_both_din_U_ack_in;

assign ipd_x_0_din = {{din_TDATA_int_regslice[15:8]}};

assign ipd_x_1_din = {{din_TDATA_int_regslice[31:24]}};

assign ipd_x_2_din = {{din_TDATA_int_regslice[47:40]}};

assign ipd_x_3_din = {{din_TDATA_int_regslice[63:56]}};

assign ipd_x_4_din = {{din_TDATA_int_regslice[79:72]}};

assign ipd_x_5_din = {{din_TDATA_int_regslice[95:88]}};

assign ipd_x_6_din = {{din_TDATA_int_regslice[111:104]}};

assign ipd_x_7_din = {{din_TDATA_int_regslice[127:120]}};

assign ipd_x_8_din = {{din_TDATA_int_regslice[143:136]}};

assign len_x_0_din = din_TDATA_int_regslice[7:0];

assign len_x_1_din = {{din_TDATA_int_regslice[23:16]}};

assign len_x_2_din = {{din_TDATA_int_regslice[39:32]}};

assign len_x_3_din = {{din_TDATA_int_regslice[55:48]}};

assign len_x_4_din = {{din_TDATA_int_regslice[71:64]}};

assign len_x_5_din = {{din_TDATA_int_regslice[87:80]}};

assign len_x_6_din = {{din_TDATA_int_regslice[103:96]}};

assign len_x_7_din = {{din_TDATA_int_regslice[119:112]}};

assign len_x_8_din = {{din_TDATA_int_regslice[135:128]}};

assign start_out = real_start;

endmodule //CNN_stream_feature_separate_layer_stream_9u_s
