# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/sidejob/ethernet_NN/kitsum_1024B_xy_20231211/kits_prj.srcs/sources_1/ip/CNN_stream_0/CNN_stream_0.xci
# IP: The module: 'CNN_stream_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/sidejob/ethernet_NN/kitsum_1024B_xy_20231211/kits_prj.srcs/sources_1/ip/CNN_stream_0/constraints/CNN_stream_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'CNN_stream_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: d:/sidejob/ethernet_NN/kitsum_1024B_xy_20231211/kits_prj.srcs/sources_1/ip/CNN_stream_0/CNN_stream_0.xci
# IP: The module: 'CNN_stream_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/sidejob/ethernet_NN/kitsum_1024B_xy_20231211/kits_prj.srcs/sources_1/ip/CNN_stream_0/constraints/CNN_stream_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'CNN_stream_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
