set SynModuleInfo {
  {SRCNAME feature_separate_layer_stream<9u> MODELNAME feature_separate_layer_stream_9u_s RTLNAME CNN_stream_feature_separate_layer_stream_9u_s
    SUBMODULES {
      {MODELNAME CNN_stream_regslice_both RTLNAME CNN_stream_regslice_both BINDTYPE interface TYPE adapter IMPL reg_slice}
    }
  }
  {SRCNAME embedding_layer_stream<9u> MODELNAME embedding_layer_stream_9u_s RTLNAME CNN_stream_embedding_layer_stream_9u_s
    SUBMODULES {
      {MODELNAME CNN_stream_embedding_layer_stream_9u_s_p_ZL26len_embedding_table_stream_0_ROM_AUTO_1R RTLNAME CNN_stream_embedding_layer_stream_9u_s_p_ZL26len_embedding_table_stream_0_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME CNN_stream_embedding_layer_stream_9u_s_p_ZL26len_embedding_table_stream_1_ROM_AUTO_1R RTLNAME CNN_stream_embedding_layer_stream_9u_s_p_ZL26len_embedding_table_stream_1_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME CNN_stream_embedding_layer_stream_9u_s_p_ZL26len_embedding_table_stream_2_ROM_AUTO_1R RTLNAME CNN_stream_embedding_layer_stream_9u_s_p_ZL26len_embedding_table_stream_2_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME CNN_stream_embedding_layer_stream_9u_s_p_ZL26len_embedding_table_stream_3_ROM_AUTO_1R RTLNAME CNN_stream_embedding_layer_stream_9u_s_p_ZL26len_embedding_table_stream_3_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME CNN_stream_embedding_layer_stream_9u_s_p_ZL26len_embedding_table_stream_4_ROM_AUTO_1R RTLNAME CNN_stream_embedding_layer_stream_9u_s_p_ZL26len_embedding_table_stream_4_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME CNN_stream_embedding_layer_stream_9u_s_p_ZL26len_embedding_table_stream_5_ROM_AUTO_1R RTLNAME CNN_stream_embedding_layer_stream_9u_s_p_ZL26len_embedding_table_stream_5_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME CNN_stream_embedding_layer_stream_9u_s_p_ZL26len_embedding_table_stream_6_ROM_AUTO_1R RTLNAME CNN_stream_embedding_layer_stream_9u_s_p_ZL26len_embedding_table_stream_6_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME CNN_stream_embedding_layer_stream_9u_s_p_ZL26len_embedding_table_stream_7_ROM_AUTO_1R RTLNAME CNN_stream_embedding_layer_stream_9u_s_p_ZL26len_embedding_table_stream_7_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME CNN_stream_embedding_layer_stream_9u_s_p_ZL26len_embedding_table_stream_8_ROM_AUTO_1R RTLNAME CNN_stream_embedding_layer_stream_9u_s_p_ZL26len_embedding_table_stream_8_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME CNN_stream_embedding_layer_stream_9u_s_p_ZL26len_embedding_table_stream_9_ROM_AUTO_1R RTLNAME CNN_stream_embedding_layer_stream_9u_s_p_ZL26len_embedding_table_stream_9_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME CNN_stream_embedding_layer_stream_9u_s_p_ZL26ipd_embedding_table_stream_0_ROM_AUTO_1R RTLNAME CNN_stream_embedding_layer_stream_9u_s_p_ZL26ipd_embedding_table_stream_0_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME CNN_stream_embedding_layer_stream_9u_s_p_ZL26ipd_embedding_table_stream_1_ROM_AUTO_1R RTLNAME CNN_stream_embedding_layer_stream_9u_s_p_ZL26ipd_embedding_table_stream_1_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME CNN_stream_embedding_layer_stream_9u_s_p_ZL26ipd_embedding_table_stream_2_ROM_AUTO_1R RTLNAME CNN_stream_embedding_layer_stream_9u_s_p_ZL26ipd_embedding_table_stream_2_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME CNN_stream_embedding_layer_stream_9u_s_p_ZL26ipd_embedding_table_stream_3_ROM_AUTO_1R RTLNAME CNN_stream_embedding_layer_stream_9u_s_p_ZL26ipd_embedding_table_stream_3_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME CNN_stream_embedding_layer_stream_9u_s_p_ZL26ipd_embedding_table_stream_4_ROM_AUTO_1R RTLNAME CNN_stream_embedding_layer_stream_9u_s_p_ZL26ipd_embedding_table_stream_4_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME CNN_stream_embedding_layer_stream_9u_s_p_ZL26ipd_embedding_table_stream_5_ROM_AUTO_1R RTLNAME CNN_stream_embedding_layer_stream_9u_s_p_ZL26ipd_embedding_table_stream_5_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME CNN_stream_embedding_layer_stream_9u_s_p_ZL26ipd_embedding_table_stream_6_ROM_AUTO_1R RTLNAME CNN_stream_embedding_layer_stream_9u_s_p_ZL26ipd_embedding_table_stream_6_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME CNN_stream_embedding_layer_stream_9u_s_p_ZL26ipd_embedding_table_stream_7_ROM_AUTO_1R RTLNAME CNN_stream_embedding_layer_stream_9u_s_p_ZL26ipd_embedding_table_stream_7_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME feature_concate_layer_stream<9u> MODELNAME feature_concate_layer_stream_9u_s RTLNAME CNN_stream_feature_concate_layer_stream_9u_s}
  {SRCNAME fully_connect_layer_stream3<9u> MODELNAME fully_connect_layer_stream3_9u_s RTLNAME CNN_stream_fully_connect_layer_stream3_9u_s
    SUBMODULES {
      {MODELNAME CNN_stream_flow_control_loop_pipe RTLNAME CNN_stream_flow_control_loop_pipe BINDTYPE interface TYPE internal_upc_flow_control INSTNAME CNN_stream_flow_control_loop_pipe_U}
    }
  }
  {SRCNAME conv2d_3_stream_layer<9u> MODELNAME conv2d_3_stream_layer_9u_s RTLNAME CNN_stream_conv2d_3_stream_layer_9u_s}
  {SRCNAME conv2d_3_stream_layer_post<9u> MODELNAME conv2d_3_stream_layer_post_9u_s RTLNAME CNN_stream_conv2d_3_stream_layer_post_9u_s}
  {SRCNAME conv2d_4_stream_layer<9u> MODELNAME conv2d_4_stream_layer_9u_s RTLNAME CNN_stream_conv2d_4_stream_layer_9u_s}
  {SRCNAME conv2d_4_stream_layer_post<9u> MODELNAME conv2d_4_stream_layer_post_9u_s RTLNAME CNN_stream_conv2d_4_stream_layer_post_9u_s}
  {SRCNAME conv2d_5_stream_layer<9u> MODELNAME conv2d_5_stream_layer_9u_s RTLNAME CNN_stream_conv2d_5_stream_layer_9u_s}
  {SRCNAME conv2d_5_stream_layer_post<9u> MODELNAME conv2d_5_stream_layer_post_9u_s RTLNAME CNN_stream_conv2d_5_stream_layer_post_9u_s}
  {SRCNAME reshape_concate_layer_stream MODELNAME reshape_concate_layer_stream RTLNAME CNN_stream_reshape_concate_layer_stream}
  {SRCNAME fully_connect2_layer_stream MODELNAME fully_connect2_layer_stream RTLNAME CNN_stream_fully_connect2_layer_stream}
  {SRCNAME l_softmax_layer_stream MODELNAME l_softmax_layer_stream RTLNAME CNN_stream_l_softmax_layer_stream
    SUBMODULES {
      {MODELNAME CNN_stream_fadd_32ns_32ns_32_10_full_dsp_1 RTLNAME CNN_stream_fadd_32ns_32ns_32_10_full_dsp_1 BINDTYPE op TYPE fadd IMPL fulldsp LATENCY 9 ALLOW_PRAGMA 1}
      {MODELNAME CNN_stream_fsub_32ns_32ns_32_10_full_dsp_1 RTLNAME CNN_stream_fsub_32ns_32ns_32_10_full_dsp_1 BINDTYPE op TYPE fsub IMPL fulldsp LATENCY 9 ALLOW_PRAGMA 1}
      {MODELNAME CNN_stream_sitofp_32ns_32_7_no_dsp_1 RTLNAME CNN_stream_sitofp_32ns_32_7_no_dsp_1 BINDTYPE op TYPE sitofp IMPL auto LATENCY 6 ALLOW_PRAGMA 1}
      {MODELNAME CNN_stream_flog_32ns_32ns_32_19_full_dsp_1 RTLNAME CNN_stream_flog_32ns_32ns_32_19_full_dsp_1 BINDTYPE op TYPE flog IMPL fulldsp LATENCY 18 ALLOW_PRAGMA 1}
      {MODELNAME CNN_stream_fexp_32ns_32ns_32_21_full_dsp_1 RTLNAME CNN_stream_fexp_32ns_32ns_32_21_full_dsp_1 BINDTYPE op TYPE fexp IMPL fulldsp LATENCY 20 ALLOW_PRAGMA 1}
      {MODELNAME CNN_stream_sparsemux_9_3_8_1_1 RTLNAME CNN_stream_sparsemux_9_3_8_1_1 BINDTYPE op TYPE sparsemux IMPL onehotencoding_realdef}
    }
  }
  {SRCNAME CNN_stream MODELNAME CNN_stream RTLNAME CNN_stream IS_TOP 1
    SUBMODULES {
      {MODELNAME CNN_stream_fifo_w8_d4_S RTLNAME CNN_stream_fifo_w8_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME len_x_U}
      {MODELNAME CNN_stream_fifo_w8_d4_S RTLNAME CNN_stream_fifo_w8_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME len_x_1_U}
      {MODELNAME CNN_stream_fifo_w8_d4_S RTLNAME CNN_stream_fifo_w8_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME len_x_2_U}
      {MODELNAME CNN_stream_fifo_w8_d4_S RTLNAME CNN_stream_fifo_w8_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME len_x_3_U}
      {MODELNAME CNN_stream_fifo_w8_d4_S RTLNAME CNN_stream_fifo_w8_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME len_x_4_U}
      {MODELNAME CNN_stream_fifo_w8_d4_S RTLNAME CNN_stream_fifo_w8_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME len_x_5_U}
      {MODELNAME CNN_stream_fifo_w8_d4_S RTLNAME CNN_stream_fifo_w8_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME len_x_6_U}
      {MODELNAME CNN_stream_fifo_w8_d4_S RTLNAME CNN_stream_fifo_w8_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME len_x_7_U}
      {MODELNAME CNN_stream_fifo_w8_d4_S RTLNAME CNN_stream_fifo_w8_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME len_x_8_U}
      {MODELNAME CNN_stream_fifo_w8_d4_S RTLNAME CNN_stream_fifo_w8_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME ipd_x_U}
      {MODELNAME CNN_stream_fifo_w8_d4_S RTLNAME CNN_stream_fifo_w8_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME ipd_x_1_U}
      {MODELNAME CNN_stream_fifo_w8_d4_S RTLNAME CNN_stream_fifo_w8_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME ipd_x_2_U}
      {MODELNAME CNN_stream_fifo_w8_d4_S RTLNAME CNN_stream_fifo_w8_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME ipd_x_3_U}
      {MODELNAME CNN_stream_fifo_w8_d4_S RTLNAME CNN_stream_fifo_w8_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME ipd_x_4_U}
      {MODELNAME CNN_stream_fifo_w8_d4_S RTLNAME CNN_stream_fifo_w8_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME ipd_x_5_U}
      {MODELNAME CNN_stream_fifo_w8_d4_S RTLNAME CNN_stream_fifo_w8_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME ipd_x_6_U}
      {MODELNAME CNN_stream_fifo_w8_d4_S RTLNAME CNN_stream_fifo_w8_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME ipd_x_7_U}
      {MODELNAME CNN_stream_fifo_w8_d4_S RTLNAME CNN_stream_fifo_w8_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME ipd_x_8_U}
      {MODELNAME CNN_stream_fifo_w320_d4_A RTLNAME CNN_stream_fifo_w320_d4_A BINDTYPE storage TYPE fifo IMPL memory ALLOW_PRAGMA 1 INSTNAME len_x_embedding_0_U}
      {MODELNAME CNN_stream_fifo_w320_d4_A RTLNAME CNN_stream_fifo_w320_d4_A BINDTYPE storage TYPE fifo IMPL memory ALLOW_PRAGMA 1 INSTNAME len_x_embedding_1_U}
      {MODELNAME CNN_stream_fifo_w320_d4_A RTLNAME CNN_stream_fifo_w320_d4_A BINDTYPE storage TYPE fifo IMPL memory ALLOW_PRAGMA 1 INSTNAME len_x_embedding_2_U}
      {MODELNAME CNN_stream_fifo_w320_d4_A RTLNAME CNN_stream_fifo_w320_d4_A BINDTYPE storage TYPE fifo IMPL memory ALLOW_PRAGMA 1 INSTNAME len_x_embedding_3_U}
      {MODELNAME CNN_stream_fifo_w320_d4_A RTLNAME CNN_stream_fifo_w320_d4_A BINDTYPE storage TYPE fifo IMPL memory ALLOW_PRAGMA 1 INSTNAME len_x_embedding_4_U}
      {MODELNAME CNN_stream_fifo_w320_d4_A RTLNAME CNN_stream_fifo_w320_d4_A BINDTYPE storage TYPE fifo IMPL memory ALLOW_PRAGMA 1 INSTNAME len_x_embedding_5_U}
      {MODELNAME CNN_stream_fifo_w320_d4_A RTLNAME CNN_stream_fifo_w320_d4_A BINDTYPE storage TYPE fifo IMPL memory ALLOW_PRAGMA 1 INSTNAME len_x_embedding_6_U}
      {MODELNAME CNN_stream_fifo_w320_d4_A RTLNAME CNN_stream_fifo_w320_d4_A BINDTYPE storage TYPE fifo IMPL memory ALLOW_PRAGMA 1 INSTNAME len_x_embedding_7_U}
      {MODELNAME CNN_stream_fifo_w320_d4_A RTLNAME CNN_stream_fifo_w320_d4_A BINDTYPE storage TYPE fifo IMPL memory ALLOW_PRAGMA 1 INSTNAME len_x_embedding_8_U}
      {MODELNAME CNN_stream_fifo_w256_d4_S RTLNAME CNN_stream_fifo_w256_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME ipd_x_embedding_0_U}
      {MODELNAME CNN_stream_fifo_w256_d4_S RTLNAME CNN_stream_fifo_w256_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME ipd_x_embedding_1_U}
      {MODELNAME CNN_stream_fifo_w256_d4_S RTLNAME CNN_stream_fifo_w256_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME ipd_x_embedding_2_U}
      {MODELNAME CNN_stream_fifo_w256_d4_S RTLNAME CNN_stream_fifo_w256_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME ipd_x_embedding_3_U}
      {MODELNAME CNN_stream_fifo_w256_d4_S RTLNAME CNN_stream_fifo_w256_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME ipd_x_embedding_4_U}
      {MODELNAME CNN_stream_fifo_w256_d4_S RTLNAME CNN_stream_fifo_w256_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME ipd_x_embedding_5_U}
      {MODELNAME CNN_stream_fifo_w256_d4_S RTLNAME CNN_stream_fifo_w256_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME ipd_x_embedding_6_U}
      {MODELNAME CNN_stream_fifo_w256_d4_S RTLNAME CNN_stream_fifo_w256_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME ipd_x_embedding_7_U}
      {MODELNAME CNN_stream_fifo_w256_d4_S RTLNAME CNN_stream_fifo_w256_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME ipd_x_embedding_8_U}
      {MODELNAME CNN_stream_fifo_w576_d4_A RTLNAME CNN_stream_fifo_w576_d4_A BINDTYPE storage TYPE fifo IMPL memory ALLOW_PRAGMA 1 INSTNAME feature_embedding_0_U}
      {MODELNAME CNN_stream_fifo_w576_d4_A RTLNAME CNN_stream_fifo_w576_d4_A BINDTYPE storage TYPE fifo IMPL memory ALLOW_PRAGMA 1 INSTNAME feature_embedding_1_U}
      {MODELNAME CNN_stream_fifo_w576_d4_A RTLNAME CNN_stream_fifo_w576_d4_A BINDTYPE storage TYPE fifo IMPL memory ALLOW_PRAGMA 1 INSTNAME feature_embedding_2_U}
      {MODELNAME CNN_stream_fifo_w576_d4_A RTLNAME CNN_stream_fifo_w576_d4_A BINDTYPE storage TYPE fifo IMPL memory ALLOW_PRAGMA 1 INSTNAME feature_embedding_3_U}
      {MODELNAME CNN_stream_fifo_w576_d4_A RTLNAME CNN_stream_fifo_w576_d4_A BINDTYPE storage TYPE fifo IMPL memory ALLOW_PRAGMA 1 INSTNAME feature_embedding_4_U}
      {MODELNAME CNN_stream_fifo_w576_d4_A RTLNAME CNN_stream_fifo_w576_d4_A BINDTYPE storage TYPE fifo IMPL memory ALLOW_PRAGMA 1 INSTNAME feature_embedding_5_U}
      {MODELNAME CNN_stream_fifo_w576_d4_A RTLNAME CNN_stream_fifo_w576_d4_A BINDTYPE storage TYPE fifo IMPL memory ALLOW_PRAGMA 1 INSTNAME feature_embedding_6_U}
      {MODELNAME CNN_stream_fifo_w576_d4_A RTLNAME CNN_stream_fifo_w576_d4_A BINDTYPE storage TYPE fifo IMPL memory ALLOW_PRAGMA 1 INSTNAME feature_embedding_7_U}
      {MODELNAME CNN_stream_fifo_w576_d4_A RTLNAME CNN_stream_fifo_w576_d4_A BINDTYPE storage TYPE fifo IMPL memory ALLOW_PRAGMA 1 INSTNAME feature_embedding_8_U}
      {MODELNAME CNN_stream_fifo_w256_d4_S RTLNAME CNN_stream_fifo_w256_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME proj_embedding3_0_0_U}
      {MODELNAME CNN_stream_fifo_w256_d4_S RTLNAME CNN_stream_fifo_w256_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME proj_embedding3_0_1_U}
      {MODELNAME CNN_stream_fifo_w256_d4_S RTLNAME CNN_stream_fifo_w256_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME proj_embedding3_0_2_U}
      {MODELNAME CNN_stream_fifo_w256_d4_S RTLNAME CNN_stream_fifo_w256_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME proj_embedding3_1_0_U}
      {MODELNAME CNN_stream_fifo_w256_d4_S RTLNAME CNN_stream_fifo_w256_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME proj_embedding3_1_1_U}
      {MODELNAME CNN_stream_fifo_w256_d4_S RTLNAME CNN_stream_fifo_w256_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME proj_embedding3_1_2_U}
      {MODELNAME CNN_stream_fifo_w256_d4_S RTLNAME CNN_stream_fifo_w256_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME proj_embedding3_2_0_U}
      {MODELNAME CNN_stream_fifo_w256_d4_S RTLNAME CNN_stream_fifo_w256_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME proj_embedding3_2_1_U}
      {MODELNAME CNN_stream_fifo_w256_d4_S RTLNAME CNN_stream_fifo_w256_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME proj_embedding3_2_2_U}
      {MODELNAME CNN_stream_fifo_w256_d4_S RTLNAME CNN_stream_fifo_w256_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME proj_embedding3_3_0_U}
      {MODELNAME CNN_stream_fifo_w256_d4_S RTLNAME CNN_stream_fifo_w256_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME proj_embedding3_3_1_U}
      {MODELNAME CNN_stream_fifo_w256_d4_S RTLNAME CNN_stream_fifo_w256_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME proj_embedding3_3_2_U}
      {MODELNAME CNN_stream_fifo_w256_d4_S RTLNAME CNN_stream_fifo_w256_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME proj_embedding3_4_0_U}
      {MODELNAME CNN_stream_fifo_w256_d4_S RTLNAME CNN_stream_fifo_w256_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME proj_embedding3_4_1_U}
      {MODELNAME CNN_stream_fifo_w256_d4_S RTLNAME CNN_stream_fifo_w256_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME proj_embedding3_4_2_U}
      {MODELNAME CNN_stream_fifo_w256_d4_S RTLNAME CNN_stream_fifo_w256_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME proj_embedding3_5_0_U}
      {MODELNAME CNN_stream_fifo_w256_d4_S RTLNAME CNN_stream_fifo_w256_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME proj_embedding3_5_1_U}
      {MODELNAME CNN_stream_fifo_w256_d4_S RTLNAME CNN_stream_fifo_w256_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME proj_embedding3_5_2_U}
      {MODELNAME CNN_stream_fifo_w256_d4_S RTLNAME CNN_stream_fifo_w256_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME proj_embedding3_6_0_U}
      {MODELNAME CNN_stream_fifo_w256_d4_S RTLNAME CNN_stream_fifo_w256_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME proj_embedding3_6_1_U}
      {MODELNAME CNN_stream_fifo_w256_d4_S RTLNAME CNN_stream_fifo_w256_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME proj_embedding3_6_2_U}
      {MODELNAME CNN_stream_fifo_w256_d4_S RTLNAME CNN_stream_fifo_w256_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME proj_embedding3_7_0_U}
      {MODELNAME CNN_stream_fifo_w256_d4_S RTLNAME CNN_stream_fifo_w256_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME proj_embedding3_7_1_U}
      {MODELNAME CNN_stream_fifo_w256_d4_S RTLNAME CNN_stream_fifo_w256_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME proj_embedding3_7_2_U}
      {MODELNAME CNN_stream_fifo_w256_d4_S RTLNAME CNN_stream_fifo_w256_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME proj_embedding4_0_0_U}
      {MODELNAME CNN_stream_fifo_w256_d4_S RTLNAME CNN_stream_fifo_w256_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME proj_embedding4_0_1_U}
      {MODELNAME CNN_stream_fifo_w256_d4_S RTLNAME CNN_stream_fifo_w256_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME proj_embedding4_0_2_U}
      {MODELNAME CNN_stream_fifo_w256_d4_S RTLNAME CNN_stream_fifo_w256_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME proj_embedding4_1_0_U}
      {MODELNAME CNN_stream_fifo_w256_d4_S RTLNAME CNN_stream_fifo_w256_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME proj_embedding4_1_1_U}
      {MODELNAME CNN_stream_fifo_w256_d4_S RTLNAME CNN_stream_fifo_w256_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME proj_embedding4_1_2_U}
      {MODELNAME CNN_stream_fifo_w256_d4_S RTLNAME CNN_stream_fifo_w256_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME proj_embedding4_2_0_U}
      {MODELNAME CNN_stream_fifo_w256_d4_S RTLNAME CNN_stream_fifo_w256_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME proj_embedding4_2_1_U}
      {MODELNAME CNN_stream_fifo_w256_d4_S RTLNAME CNN_stream_fifo_w256_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME proj_embedding4_2_2_U}
      {MODELNAME CNN_stream_fifo_w256_d4_S RTLNAME CNN_stream_fifo_w256_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME proj_embedding4_3_0_U}
      {MODELNAME CNN_stream_fifo_w256_d4_S RTLNAME CNN_stream_fifo_w256_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME proj_embedding4_3_1_U}
      {MODELNAME CNN_stream_fifo_w256_d4_S RTLNAME CNN_stream_fifo_w256_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME proj_embedding4_3_2_U}
      {MODELNAME CNN_stream_fifo_w256_d4_S RTLNAME CNN_stream_fifo_w256_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME proj_embedding4_4_0_U}
      {MODELNAME CNN_stream_fifo_w256_d4_S RTLNAME CNN_stream_fifo_w256_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME proj_embedding4_4_1_U}
      {MODELNAME CNN_stream_fifo_w256_d4_S RTLNAME CNN_stream_fifo_w256_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME proj_embedding4_4_2_U}
      {MODELNAME CNN_stream_fifo_w256_d4_S RTLNAME CNN_stream_fifo_w256_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME proj_embedding4_5_0_U}
      {MODELNAME CNN_stream_fifo_w256_d4_S RTLNAME CNN_stream_fifo_w256_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME proj_embedding4_5_1_U}
      {MODELNAME CNN_stream_fifo_w256_d4_S RTLNAME CNN_stream_fifo_w256_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME proj_embedding4_5_2_U}
      {MODELNAME CNN_stream_fifo_w256_d4_S RTLNAME CNN_stream_fifo_w256_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME proj_embedding4_6_0_U}
      {MODELNAME CNN_stream_fifo_w256_d4_S RTLNAME CNN_stream_fifo_w256_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME proj_embedding4_6_1_U}
      {MODELNAME CNN_stream_fifo_w256_d4_S RTLNAME CNN_stream_fifo_w256_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME proj_embedding4_6_2_U}
      {MODELNAME CNN_stream_fifo_w256_d4_S RTLNAME CNN_stream_fifo_w256_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME proj_embedding4_7_0_U}
      {MODELNAME CNN_stream_fifo_w256_d4_S RTLNAME CNN_stream_fifo_w256_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME proj_embedding4_7_1_U}
      {MODELNAME CNN_stream_fifo_w256_d4_S RTLNAME CNN_stream_fifo_w256_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME proj_embedding4_7_2_U}
      {MODELNAME CNN_stream_fifo_w256_d4_S RTLNAME CNN_stream_fifo_w256_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME proj_embedding5_0_0_U}
      {MODELNAME CNN_stream_fifo_w256_d4_S RTLNAME CNN_stream_fifo_w256_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME proj_embedding5_0_1_U}
      {MODELNAME CNN_stream_fifo_w256_d4_S RTLNAME CNN_stream_fifo_w256_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME proj_embedding5_0_2_U}
      {MODELNAME CNN_stream_fifo_w256_d4_S RTLNAME CNN_stream_fifo_w256_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME proj_embedding5_1_0_U}
      {MODELNAME CNN_stream_fifo_w256_d4_S RTLNAME CNN_stream_fifo_w256_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME proj_embedding5_1_1_U}
      {MODELNAME CNN_stream_fifo_w256_d4_S RTLNAME CNN_stream_fifo_w256_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME proj_embedding5_1_2_U}
      {MODELNAME CNN_stream_fifo_w256_d4_S RTLNAME CNN_stream_fifo_w256_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME proj_embedding5_2_0_U}
      {MODELNAME CNN_stream_fifo_w256_d4_S RTLNAME CNN_stream_fifo_w256_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME proj_embedding5_2_1_U}
      {MODELNAME CNN_stream_fifo_w256_d4_S RTLNAME CNN_stream_fifo_w256_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME proj_embedding5_2_2_U}
      {MODELNAME CNN_stream_fifo_w256_d4_S RTLNAME CNN_stream_fifo_w256_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME proj_embedding5_3_0_U}
      {MODELNAME CNN_stream_fifo_w256_d4_S RTLNAME CNN_stream_fifo_w256_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME proj_embedding5_3_1_U}
      {MODELNAME CNN_stream_fifo_w256_d4_S RTLNAME CNN_stream_fifo_w256_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME proj_embedding5_3_2_U}
      {MODELNAME CNN_stream_fifo_w256_d4_S RTLNAME CNN_stream_fifo_w256_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME proj_embedding5_4_0_U}
      {MODELNAME CNN_stream_fifo_w256_d4_S RTLNAME CNN_stream_fifo_w256_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME proj_embedding5_4_1_U}
      {MODELNAME CNN_stream_fifo_w256_d4_S RTLNAME CNN_stream_fifo_w256_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME proj_embedding5_4_2_U}
      {MODELNAME CNN_stream_fifo_w256_d4_S RTLNAME CNN_stream_fifo_w256_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME proj_embedding5_5_0_U}
      {MODELNAME CNN_stream_fifo_w256_d4_S RTLNAME CNN_stream_fifo_w256_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME proj_embedding5_5_1_U}
      {MODELNAME CNN_stream_fifo_w256_d4_S RTLNAME CNN_stream_fifo_w256_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME proj_embedding5_5_2_U}
      {MODELNAME CNN_stream_fifo_w256_d4_S RTLNAME CNN_stream_fifo_w256_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME proj_embedding5_6_0_U}
      {MODELNAME CNN_stream_fifo_w256_d4_S RTLNAME CNN_stream_fifo_w256_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME proj_embedding5_6_1_U}
      {MODELNAME CNN_stream_fifo_w256_d4_S RTLNAME CNN_stream_fifo_w256_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME proj_embedding5_6_2_U}
      {MODELNAME CNN_stream_fifo_w256_d4_S RTLNAME CNN_stream_fifo_w256_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME proj_embedding5_7_0_U}
      {MODELNAME CNN_stream_fifo_w256_d4_S RTLNAME CNN_stream_fifo_w256_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME proj_embedding5_7_1_U}
      {MODELNAME CNN_stream_fifo_w256_d4_S RTLNAME CNN_stream_fifo_w256_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME proj_embedding5_7_2_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out3_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out3_1_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out3_2_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out3_3_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out3_4_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out3_5_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out3_6_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out3_7_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out3_8_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out3_9_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out3_10_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out3_11_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out3_12_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out3_13_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out3_14_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out3_15_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out3_16_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out3_17_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out3_18_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out3_19_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out3_20_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out3_21_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out3_22_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out3_23_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out3_24_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out3_25_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out3_26_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out3_27_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out3_28_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out3_29_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out3_30_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out3_31_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out3_32_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out3_33_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out3_34_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out3_35_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out3_36_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out3_37_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out3_38_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out3_39_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out3_40_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out3_41_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out3_42_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out3_43_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out3_44_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out3_45_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out3_46_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out3_47_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out3_48_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out3_49_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out3_50_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out3_51_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out3_52_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out3_53_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME conv_out3_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME conv_out3_1_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME conv_out3_2_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME conv_out3_3_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME conv_out3_4_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME conv_out3_5_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME conv_out3_6_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME conv_out3_7_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME conv_out3_8_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME conv_out3_9_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME conv_out3_10_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME conv_out3_11_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME conv_out3_12_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME conv_out3_13_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out4_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out4_1_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out4_2_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out4_3_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out4_4_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out4_5_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out4_6_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out4_7_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out4_8_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out4_9_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out4_10_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out4_11_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out4_12_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out4_13_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out4_14_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out4_15_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out4_16_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out4_17_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out4_18_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out4_19_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out4_20_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out4_21_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out4_22_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out4_23_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out4_24_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out4_25_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out4_26_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out4_27_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out4_28_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out4_29_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out4_30_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out4_31_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out4_32_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out4_33_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out4_34_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out4_35_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out4_36_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out4_37_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out4_38_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out4_39_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out4_40_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out4_41_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out4_42_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out4_43_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out4_44_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out4_45_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out4_46_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out4_47_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out4_48_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out4_49_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out4_50_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out4_51_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out4_52_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out4_53_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out4_54_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out4_55_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out4_56_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out4_57_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out4_58_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out4_59_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out4_60_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out4_61_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out4_62_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out4_63_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out4_64_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out4_65_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out4_66_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out4_67_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out4_68_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out4_69_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out4_70_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out4_71_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME conv_out4_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME conv_out4_1_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME conv_out4_2_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME conv_out4_3_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME conv_out4_4_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME conv_out4_5_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME conv_out4_6_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME conv_out4_7_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME conv_out4_8_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME conv_out4_9_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME conv_out4_10_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME conv_out4_11_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out5_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out5_1_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out5_2_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out5_3_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out5_4_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out5_5_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out5_6_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out5_7_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out5_8_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out5_9_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out5_10_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out5_11_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out5_12_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out5_13_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out5_14_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out5_15_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out5_16_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out5_17_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out5_18_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out5_19_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out5_20_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out5_21_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out5_22_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out5_23_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out5_24_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out5_25_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out5_26_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out5_27_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out5_28_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out5_29_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out5_30_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out5_31_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out5_32_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out5_33_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out5_34_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out5_35_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out5_36_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out5_37_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out5_38_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out5_39_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out5_40_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out5_41_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out5_42_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out5_43_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out5_44_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out5_45_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out5_46_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out5_47_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out5_48_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out5_49_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out5_50_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out5_51_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out5_52_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out5_53_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out5_54_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out5_55_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out5_56_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out5_57_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out5_58_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out5_59_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out5_60_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out5_61_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out5_62_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out5_63_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out5_64_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out5_65_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out5_66_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out5_67_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out5_68_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out5_69_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out5_70_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out5_71_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out5_72_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out5_73_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out5_74_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out5_75_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out5_76_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out5_77_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out5_78_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out5_79_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out5_80_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out5_81_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out5_82_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out5_83_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out5_84_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out5_85_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out5_86_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out5_87_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out5_88_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sum_out5_89_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME conv_out5_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME conv_out5_1_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME conv_out5_2_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME conv_out5_3_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME conv_out5_4_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME conv_out5_5_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME conv_out5_6_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME conv_out5_7_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME conv_out5_8_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME conv_out5_9_U}
      {MODELNAME CNN_stream_fifo_w1152_d4_A RTLNAME CNN_stream_fifo_w1152_d4_A BINDTYPE storage TYPE fifo IMPL memory ALLOW_PRAGMA 1 INSTNAME feature2_embedding_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME fc2_embedding_U}
      {MODELNAME CNN_stream_fifo_w32_d4_S RTLNAME CNN_stream_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME fc2_embedding_1_U}
      {MODELNAME CNN_stream_start_for_embedding_layer_stream_9u_U0 RTLNAME CNN_stream_start_for_embedding_layer_stream_9u_U0 BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME start_for_embedding_layer_stream_9u_U0_U}
      {MODELNAME CNN_stream_start_for_feature_concate_layer_stream_9u_U0 RTLNAME CNN_stream_start_for_feature_concate_layer_stream_9u_U0 BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME start_for_feature_concate_layer_stream_9u_U0_U}
      {MODELNAME CNN_stream_start_for_fully_connect_layer_stream3_9u_U0 RTLNAME CNN_stream_start_for_fully_connect_layer_stream3_9u_U0 BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME start_for_fully_connect_layer_stream3_9u_U0_U}
      {MODELNAME CNN_stream_start_for_conv2d_3_stream_layer_9u_U0 RTLNAME CNN_stream_start_for_conv2d_3_stream_layer_9u_U0 BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME start_for_conv2d_3_stream_layer_9u_U0_U}
      {MODELNAME CNN_stream_start_for_conv2d_4_stream_layer_9u_U0 RTLNAME CNN_stream_start_for_conv2d_4_stream_layer_9u_U0 BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME start_for_conv2d_4_stream_layer_9u_U0_U}
      {MODELNAME CNN_stream_start_for_conv2d_5_stream_layer_9u_U0 RTLNAME CNN_stream_start_for_conv2d_5_stream_layer_9u_U0 BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME start_for_conv2d_5_stream_layer_9u_U0_U}
      {MODELNAME CNN_stream_start_for_conv2d_3_stream_layer_post_9u_U0 RTLNAME CNN_stream_start_for_conv2d_3_stream_layer_post_9u_U0 BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME start_for_conv2d_3_stream_layer_post_9u_U0_U}
      {MODELNAME CNN_stream_start_for_reshape_concate_layer_stream_U0 RTLNAME CNN_stream_start_for_reshape_concate_layer_stream_U0 BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME start_for_reshape_concate_layer_stream_U0_U}
      {MODELNAME CNN_stream_start_for_conv2d_4_stream_layer_post_9u_U0 RTLNAME CNN_stream_start_for_conv2d_4_stream_layer_post_9u_U0 BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME start_for_conv2d_4_stream_layer_post_9u_U0_U}
      {MODELNAME CNN_stream_start_for_conv2d_5_stream_layer_post_9u_U0 RTLNAME CNN_stream_start_for_conv2d_5_stream_layer_post_9u_U0 BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME start_for_conv2d_5_stream_layer_post_9u_U0_U}
      {MODELNAME CNN_stream_start_for_fully_connect2_layer_stream_U0 RTLNAME CNN_stream_start_for_fully_connect2_layer_stream_U0 BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME start_for_fully_connect2_layer_stream_U0_U}
      {MODELNAME CNN_stream_start_for_l_softmax_layer_stream_U0 RTLNAME CNN_stream_start_for_l_softmax_layer_stream_U0 BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME start_for_l_softmax_layer_stream_U0_U}
    }
  }
}
