# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/sidejob/kitsum_1024B_xy_20231211/kits_prj.srcs/sources_1/IP/fifo_gen_axis1024/fifo_gen_axis1024.xci
# IP: The module: 'fifo_gen_axis1024' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/sidejob/kitsum_1024B_xy_20231211/kits_prj.srcs/sources_1/IP/fifo_gen_axis1024/fifo_gen_axis1024.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_gen_axis1024'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/sidejob/kitsum_1024B_xy_20231211/kits_prj.srcs/sources_1/IP/fifo_gen_axis1024/fifo_gen_axis1024_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_gen_axis1024'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: D:/sidejob/kitsum_1024B_xy_20231211/kits_prj.srcs/sources_1/IP/fifo_gen_axis1024/fifo_gen_axis1024.xci
# IP: The module: 'fifo_gen_axis1024' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/sidejob/kitsum_1024B_xy_20231211/kits_prj.srcs/sources_1/IP/fifo_gen_axis1024/fifo_gen_axis1024.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_gen_axis1024'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/sidejob/kitsum_1024B_xy_20231211/kits_prj.srcs/sources_1/IP/fifo_gen_axis1024/fifo_gen_axis1024_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_gen_axis1024'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
