# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/sidejob/ethernet_NN/kitsum_1024B_xy_20231211/kits_prj.srcs/sources_1/ip/xxv_ethernet_25_x0y2/xxv_ethernet_25_x0y2.xci
# IP: The module: 'xxv_ethernet_25_x0y2' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: d:/sidejob/ethernet_NN/kitsum_1024B_xy_20231211/kits_prj.srcs/sources_1/ip/xxv_ethernet_25_x0y2/ip_0/xxv_ethernet_25_x0y2_gt.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==xxv_ethernet_25_x0y2_gt || ORIG_REF_NAME==xxv_ethernet_25_x0y2_gt} -quiet] -quiet

# IP: d:/sidejob/ethernet_NN/kitsum_1024B_xy_20231211/kits_prj.srcs/sources_1/ip/xxv_ethernet_25_x0y2/ip_1/xxv_ethernet_25_x0y2_gt_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==xxv_ethernet_25_x0y2_gt_1 || ORIG_REF_NAME==xxv_ethernet_25_x0y2_gt_1} -quiet] -quiet

# IP: d:/sidejob/ethernet_NN/kitsum_1024B_xy_20231211/kits_prj.srcs/sources_1/ip/xxv_ethernet_25_x0y2/ip_2/xxv_ethernet_25_x0y2_gt_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==xxv_ethernet_25_x0y2_gt_2 || ORIG_REF_NAME==xxv_ethernet_25_x0y2_gt_2} -quiet] -quiet

# IP: d:/sidejob/ethernet_NN/kitsum_1024B_xy_20231211/kits_prj.srcs/sources_1/ip/xxv_ethernet_25_x0y2/ip_3/xxv_ethernet_25_x0y2_gt_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==xxv_ethernet_25_x0y2_gt_3 || ORIG_REF_NAME==xxv_ethernet_25_x0y2_gt_3} -quiet] -quiet

# XDC: d:/sidejob/ethernet_NN/kitsum_1024B_xy_20231211/kits_prj.srcs/sources_1/ip/xxv_ethernet_25_x0y2/ip_0/synth/xxv_ethernet_25_x0y2_gt_ooc.xdc

# XDC: d:/sidejob/ethernet_NN/kitsum_1024B_xy_20231211/kits_prj.srcs/sources_1/ip/xxv_ethernet_25_x0y2/ip_0/synth/xxv_ethernet_25_x0y2_gt.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==xxv_ethernet_25_x0y2_gt || ORIG_REF_NAME==xxv_ethernet_25_x0y2_gt} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/sidejob/ethernet_NN/kitsum_1024B_xy_20231211/kits_prj.srcs/sources_1/ip/xxv_ethernet_25_x0y2/synth/xxv_ethernet_25_x0y2_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'xxv_ethernet_25_x0y2'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/sidejob/ethernet_NN/kitsum_1024B_xy_20231211/kits_prj.srcs/sources_1/ip/xxv_ethernet_25_x0y2/synth/xxv_ethernet_25_x0y2.xdc
# XDC: The top module name and the constraint reference have the same name: 'xxv_ethernet_25_x0y2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/sidejob/ethernet_NN/kitsum_1024B_xy_20231211/kits_prj.srcs/sources_1/ip/xxv_ethernet_25_x0y2/synth/xxv_ethernet_25_x0y2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'xxv_ethernet_25_x0y2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/sidejob/ethernet_NN/kitsum_1024B_xy_20231211/kits_prj.srcs/sources_1/ip/xxv_ethernet_25_x0y2/ip_1/synth/xxv_ethernet_25_x0y2_gt_1_ooc.xdc

# XDC: d:/sidejob/ethernet_NN/kitsum_1024B_xy_20231211/kits_prj.srcs/sources_1/ip/xxv_ethernet_25_x0y2/ip_1/synth/xxv_ethernet_25_x0y2_gt_1.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==xxv_ethernet_25_x0y2_gt_1 || ORIG_REF_NAME==xxv_ethernet_25_x0y2_gt_1} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/sidejob/ethernet_NN/kitsum_1024B_xy_20231211/kits_prj.srcs/sources_1/ip/xxv_ethernet_25_x0y2/ip_2/synth/xxv_ethernet_25_x0y2_gt_2_ooc.xdc

# XDC: d:/sidejob/ethernet_NN/kitsum_1024B_xy_20231211/kits_prj.srcs/sources_1/ip/xxv_ethernet_25_x0y2/ip_2/synth/xxv_ethernet_25_x0y2_gt_2.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==xxv_ethernet_25_x0y2_gt_2 || ORIG_REF_NAME==xxv_ethernet_25_x0y2_gt_2} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/sidejob/ethernet_NN/kitsum_1024B_xy_20231211/kits_prj.srcs/sources_1/ip/xxv_ethernet_25_x0y2/ip_3/synth/xxv_ethernet_25_x0y2_gt_3_ooc.xdc

# XDC: d:/sidejob/ethernet_NN/kitsum_1024B_xy_20231211/kits_prj.srcs/sources_1/ip/xxv_ethernet_25_x0y2/ip_3/synth/xxv_ethernet_25_x0y2_gt_3.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==xxv_ethernet_25_x0y2_gt_3 || ORIG_REF_NAME==xxv_ethernet_25_x0y2_gt_3} -quiet] {/inst } ]/inst ] -quiet] -quiet

# IP: D:/sidejob/ethernet_NN/kitsum_1024B_xy_20231211/kits_prj.srcs/sources_1/ip/xxv_ethernet_25_x0y2/xxv_ethernet_25_x0y2.xci
# IP: The module: 'xxv_ethernet_25_x0y2' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: d:/sidejob/ethernet_NN/kitsum_1024B_xy_20231211/kits_prj.srcs/sources_1/ip/xxv_ethernet_25_x0y2/ip_0/xxv_ethernet_25_x0y2_gt.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==xxv_ethernet_25_x0y2_gt || ORIG_REF_NAME==xxv_ethernet_25_x0y2_gt} -quiet] -quiet

# IP: d:/sidejob/ethernet_NN/kitsum_1024B_xy_20231211/kits_prj.srcs/sources_1/ip/xxv_ethernet_25_x0y2/ip_1/xxv_ethernet_25_x0y2_gt_1.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==xxv_ethernet_25_x0y2_gt_1 || ORIG_REF_NAME==xxv_ethernet_25_x0y2_gt_1} -quiet] -quiet

# IP: d:/sidejob/ethernet_NN/kitsum_1024B_xy_20231211/kits_prj.srcs/sources_1/ip/xxv_ethernet_25_x0y2/ip_2/xxv_ethernet_25_x0y2_gt_2.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==xxv_ethernet_25_x0y2_gt_2 || ORIG_REF_NAME==xxv_ethernet_25_x0y2_gt_2} -quiet] -quiet

# IP: d:/sidejob/ethernet_NN/kitsum_1024B_xy_20231211/kits_prj.srcs/sources_1/ip/xxv_ethernet_25_x0y2/ip_3/xxv_ethernet_25_x0y2_gt_3.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==xxv_ethernet_25_x0y2_gt_3 || ORIG_REF_NAME==xxv_ethernet_25_x0y2_gt_3} -quiet] -quiet

# XDC: d:/sidejob/ethernet_NN/kitsum_1024B_xy_20231211/kits_prj.srcs/sources_1/ip/xxv_ethernet_25_x0y2/ip_0/synth/xxv_ethernet_25_x0y2_gt_ooc.xdc

# XDC: d:/sidejob/ethernet_NN/kitsum_1024B_xy_20231211/kits_prj.srcs/sources_1/ip/xxv_ethernet_25_x0y2/ip_0/synth/xxv_ethernet_25_x0y2_gt.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==xxv_ethernet_25_x0y2_gt || ORIG_REF_NAME==xxv_ethernet_25_x0y2_gt} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/sidejob/ethernet_NN/kitsum_1024B_xy_20231211/kits_prj.srcs/sources_1/ip/xxv_ethernet_25_x0y2/synth/xxv_ethernet_25_x0y2_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'xxv_ethernet_25_x0y2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/sidejob/ethernet_NN/kitsum_1024B_xy_20231211/kits_prj.srcs/sources_1/ip/xxv_ethernet_25_x0y2/synth/xxv_ethernet_25_x0y2.xdc
# XDC: The top module name and the constraint reference have the same name: 'xxv_ethernet_25_x0y2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/sidejob/ethernet_NN/kitsum_1024B_xy_20231211/kits_prj.srcs/sources_1/ip/xxv_ethernet_25_x0y2/synth/xxv_ethernet_25_x0y2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'xxv_ethernet_25_x0y2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/sidejob/ethernet_NN/kitsum_1024B_xy_20231211/kits_prj.srcs/sources_1/ip/xxv_ethernet_25_x0y2/ip_1/synth/xxv_ethernet_25_x0y2_gt_1_ooc.xdc

# XDC: d:/sidejob/ethernet_NN/kitsum_1024B_xy_20231211/kits_prj.srcs/sources_1/ip/xxv_ethernet_25_x0y2/ip_1/synth/xxv_ethernet_25_x0y2_gt_1.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==xxv_ethernet_25_x0y2_gt_1 || ORIG_REF_NAME==xxv_ethernet_25_x0y2_gt_1} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/sidejob/ethernet_NN/kitsum_1024B_xy_20231211/kits_prj.srcs/sources_1/ip/xxv_ethernet_25_x0y2/ip_2/synth/xxv_ethernet_25_x0y2_gt_2_ooc.xdc

# XDC: d:/sidejob/ethernet_NN/kitsum_1024B_xy_20231211/kits_prj.srcs/sources_1/ip/xxv_ethernet_25_x0y2/ip_2/synth/xxv_ethernet_25_x0y2_gt_2.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==xxv_ethernet_25_x0y2_gt_2 || ORIG_REF_NAME==xxv_ethernet_25_x0y2_gt_2} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/sidejob/ethernet_NN/kitsum_1024B_xy_20231211/kits_prj.srcs/sources_1/ip/xxv_ethernet_25_x0y2/ip_3/synth/xxv_ethernet_25_x0y2_gt_3_ooc.xdc

# XDC: d:/sidejob/ethernet_NN/kitsum_1024B_xy_20231211/kits_prj.srcs/sources_1/ip/xxv_ethernet_25_x0y2/ip_3/synth/xxv_ethernet_25_x0y2_gt_3.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==xxv_ethernet_25_x0y2_gt_3 || ORIG_REF_NAME==xxv_ethernet_25_x0y2_gt_3} -quiet] {/inst } ]/inst ] -quiet] -quiet
