-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity CNN_stream_reshape_concate_layer_stream is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    start_full_n : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    start_out : OUT STD_LOGIC;
    start_write : OUT STD_LOGIC;
    conv_out3_0_0_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    conv_out3_0_0_empty_n : IN STD_LOGIC;
    conv_out3_0_0_read : OUT STD_LOGIC;
    conv_out3_0_0_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    conv_out3_0_0_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    conv_out3_0_1_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    conv_out3_0_1_empty_n : IN STD_LOGIC;
    conv_out3_0_1_read : OUT STD_LOGIC;
    conv_out3_0_1_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    conv_out3_0_1_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    conv_out3_0_2_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    conv_out3_0_2_empty_n : IN STD_LOGIC;
    conv_out3_0_2_read : OUT STD_LOGIC;
    conv_out3_0_2_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    conv_out3_0_2_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    conv_out3_0_3_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    conv_out3_0_3_empty_n : IN STD_LOGIC;
    conv_out3_0_3_read : OUT STD_LOGIC;
    conv_out3_0_3_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    conv_out3_0_3_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    conv_out3_0_4_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    conv_out3_0_4_empty_n : IN STD_LOGIC;
    conv_out3_0_4_read : OUT STD_LOGIC;
    conv_out3_0_4_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    conv_out3_0_4_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    conv_out3_0_5_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    conv_out3_0_5_empty_n : IN STD_LOGIC;
    conv_out3_0_5_read : OUT STD_LOGIC;
    conv_out3_0_5_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    conv_out3_0_5_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    conv_out3_0_6_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    conv_out3_0_6_empty_n : IN STD_LOGIC;
    conv_out3_0_6_read : OUT STD_LOGIC;
    conv_out3_0_6_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    conv_out3_0_6_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    conv_out3_1_0_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    conv_out3_1_0_empty_n : IN STD_LOGIC;
    conv_out3_1_0_read : OUT STD_LOGIC;
    conv_out3_1_0_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    conv_out3_1_0_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    conv_out3_1_1_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    conv_out3_1_1_empty_n : IN STD_LOGIC;
    conv_out3_1_1_read : OUT STD_LOGIC;
    conv_out3_1_1_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    conv_out3_1_1_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    conv_out3_1_2_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    conv_out3_1_2_empty_n : IN STD_LOGIC;
    conv_out3_1_2_read : OUT STD_LOGIC;
    conv_out3_1_2_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    conv_out3_1_2_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    conv_out3_1_3_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    conv_out3_1_3_empty_n : IN STD_LOGIC;
    conv_out3_1_3_read : OUT STD_LOGIC;
    conv_out3_1_3_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    conv_out3_1_3_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    conv_out3_1_4_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    conv_out3_1_4_empty_n : IN STD_LOGIC;
    conv_out3_1_4_read : OUT STD_LOGIC;
    conv_out3_1_4_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    conv_out3_1_4_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    conv_out3_1_5_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    conv_out3_1_5_empty_n : IN STD_LOGIC;
    conv_out3_1_5_read : OUT STD_LOGIC;
    conv_out3_1_5_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    conv_out3_1_5_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    conv_out3_1_6_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    conv_out3_1_6_empty_n : IN STD_LOGIC;
    conv_out3_1_6_read : OUT STD_LOGIC;
    conv_out3_1_6_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    conv_out3_1_6_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    conv_out4_0_0_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    conv_out4_0_0_empty_n : IN STD_LOGIC;
    conv_out4_0_0_read : OUT STD_LOGIC;
    conv_out4_0_0_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    conv_out4_0_0_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    conv_out4_0_1_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    conv_out4_0_1_empty_n : IN STD_LOGIC;
    conv_out4_0_1_read : OUT STD_LOGIC;
    conv_out4_0_1_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    conv_out4_0_1_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    conv_out4_0_2_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    conv_out4_0_2_empty_n : IN STD_LOGIC;
    conv_out4_0_2_read : OUT STD_LOGIC;
    conv_out4_0_2_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    conv_out4_0_2_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    conv_out4_0_3_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    conv_out4_0_3_empty_n : IN STD_LOGIC;
    conv_out4_0_3_read : OUT STD_LOGIC;
    conv_out4_0_3_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    conv_out4_0_3_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    conv_out4_0_4_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    conv_out4_0_4_empty_n : IN STD_LOGIC;
    conv_out4_0_4_read : OUT STD_LOGIC;
    conv_out4_0_4_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    conv_out4_0_4_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    conv_out4_0_5_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    conv_out4_0_5_empty_n : IN STD_LOGIC;
    conv_out4_0_5_read : OUT STD_LOGIC;
    conv_out4_0_5_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    conv_out4_0_5_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    conv_out4_1_0_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    conv_out4_1_0_empty_n : IN STD_LOGIC;
    conv_out4_1_0_read : OUT STD_LOGIC;
    conv_out4_1_0_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    conv_out4_1_0_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    conv_out4_1_1_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    conv_out4_1_1_empty_n : IN STD_LOGIC;
    conv_out4_1_1_read : OUT STD_LOGIC;
    conv_out4_1_1_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    conv_out4_1_1_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    conv_out4_1_2_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    conv_out4_1_2_empty_n : IN STD_LOGIC;
    conv_out4_1_2_read : OUT STD_LOGIC;
    conv_out4_1_2_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    conv_out4_1_2_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    conv_out4_1_3_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    conv_out4_1_3_empty_n : IN STD_LOGIC;
    conv_out4_1_3_read : OUT STD_LOGIC;
    conv_out4_1_3_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    conv_out4_1_3_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    conv_out4_1_4_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    conv_out4_1_4_empty_n : IN STD_LOGIC;
    conv_out4_1_4_read : OUT STD_LOGIC;
    conv_out4_1_4_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    conv_out4_1_4_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    conv_out4_1_5_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    conv_out4_1_5_empty_n : IN STD_LOGIC;
    conv_out4_1_5_read : OUT STD_LOGIC;
    conv_out4_1_5_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    conv_out4_1_5_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    conv_out5_0_0_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    conv_out5_0_0_empty_n : IN STD_LOGIC;
    conv_out5_0_0_read : OUT STD_LOGIC;
    conv_out5_0_0_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    conv_out5_0_0_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    conv_out5_0_1_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    conv_out5_0_1_empty_n : IN STD_LOGIC;
    conv_out5_0_1_read : OUT STD_LOGIC;
    conv_out5_0_1_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    conv_out5_0_1_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    conv_out5_0_2_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    conv_out5_0_2_empty_n : IN STD_LOGIC;
    conv_out5_0_2_read : OUT STD_LOGIC;
    conv_out5_0_2_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    conv_out5_0_2_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    conv_out5_0_3_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    conv_out5_0_3_empty_n : IN STD_LOGIC;
    conv_out5_0_3_read : OUT STD_LOGIC;
    conv_out5_0_3_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    conv_out5_0_3_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    conv_out5_0_4_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    conv_out5_0_4_empty_n : IN STD_LOGIC;
    conv_out5_0_4_read : OUT STD_LOGIC;
    conv_out5_0_4_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    conv_out5_0_4_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    conv_out5_1_0_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    conv_out5_1_0_empty_n : IN STD_LOGIC;
    conv_out5_1_0_read : OUT STD_LOGIC;
    conv_out5_1_0_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    conv_out5_1_0_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    conv_out5_1_1_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    conv_out5_1_1_empty_n : IN STD_LOGIC;
    conv_out5_1_1_read : OUT STD_LOGIC;
    conv_out5_1_1_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    conv_out5_1_1_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    conv_out5_1_2_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    conv_out5_1_2_empty_n : IN STD_LOGIC;
    conv_out5_1_2_read : OUT STD_LOGIC;
    conv_out5_1_2_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    conv_out5_1_2_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    conv_out5_1_3_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    conv_out5_1_3_empty_n : IN STD_LOGIC;
    conv_out5_1_3_read : OUT STD_LOGIC;
    conv_out5_1_3_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    conv_out5_1_3_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    conv_out5_1_4_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    conv_out5_1_4_empty_n : IN STD_LOGIC;
    conv_out5_1_4_read : OUT STD_LOGIC;
    conv_out5_1_4_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    conv_out5_1_4_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    feature2_embedding_din : OUT STD_LOGIC_VECTOR (1151 downto 0);
    feature2_embedding_full_n : IN STD_LOGIC;
    feature2_embedding_write : OUT STD_LOGIC;
    feature2_embedding_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    feature2_embedding_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0) );
end;


architecture behav of CNN_stream_reshape_concate_layer_stream is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_0 : BOOLEAN := false;

attribute shreg_extract : string;
    signal real_start : STD_LOGIC;
    signal start_once_reg : STD_LOGIC := '0';
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal internal_ap_ready : STD_LOGIC;
    signal conv_out3_0_0_blk_n : STD_LOGIC;
    signal conv_out3_0_1_blk_n : STD_LOGIC;
    signal conv_out3_0_2_blk_n : STD_LOGIC;
    signal conv_out3_0_3_blk_n : STD_LOGIC;
    signal conv_out3_0_4_blk_n : STD_LOGIC;
    signal conv_out3_0_5_blk_n : STD_LOGIC;
    signal conv_out3_0_6_blk_n : STD_LOGIC;
    signal conv_out3_1_0_blk_n : STD_LOGIC;
    signal conv_out3_1_1_blk_n : STD_LOGIC;
    signal conv_out3_1_2_blk_n : STD_LOGIC;
    signal conv_out3_1_3_blk_n : STD_LOGIC;
    signal conv_out3_1_4_blk_n : STD_LOGIC;
    signal conv_out3_1_5_blk_n : STD_LOGIC;
    signal conv_out3_1_6_blk_n : STD_LOGIC;
    signal conv_out4_0_0_blk_n : STD_LOGIC;
    signal conv_out4_0_1_blk_n : STD_LOGIC;
    signal conv_out4_0_2_blk_n : STD_LOGIC;
    signal conv_out4_0_3_blk_n : STD_LOGIC;
    signal conv_out4_0_4_blk_n : STD_LOGIC;
    signal conv_out4_0_5_blk_n : STD_LOGIC;
    signal conv_out4_1_0_blk_n : STD_LOGIC;
    signal conv_out4_1_1_blk_n : STD_LOGIC;
    signal conv_out4_1_2_blk_n : STD_LOGIC;
    signal conv_out4_1_3_blk_n : STD_LOGIC;
    signal conv_out4_1_4_blk_n : STD_LOGIC;
    signal conv_out4_1_5_blk_n : STD_LOGIC;
    signal conv_out5_0_0_blk_n : STD_LOGIC;
    signal conv_out5_0_1_blk_n : STD_LOGIC;
    signal conv_out5_0_2_blk_n : STD_LOGIC;
    signal conv_out5_0_3_blk_n : STD_LOGIC;
    signal conv_out5_0_4_blk_n : STD_LOGIC;
    signal conv_out5_1_0_blk_n : STD_LOGIC;
    signal conv_out5_1_1_blk_n : STD_LOGIC;
    signal conv_out5_1_2_blk_n : STD_LOGIC;
    signal conv_out5_1_3_blk_n : STD_LOGIC;
    signal conv_out5_1_4_blk_n : STD_LOGIC;
    signal feature2_embedding_blk_n : STD_LOGIC;
    signal ap_block_state1 : BOOLEAN;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;


begin




    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    start_once_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                start_once_reg <= ap_const_logic_0;
            else
                if (((real_start = ap_const_logic_1) and (internal_ap_ready = ap_const_logic_0))) then 
                    start_once_reg <= ap_const_logic_1;
                elsif ((internal_ap_ready = ap_const_logic_1)) then 
                    start_once_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, ap_block_state1)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_block_state1)
    begin
        if ((ap_const_boolean_1 = ap_block_state1)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_assign_proc : process(real_start, ap_done_reg, conv_out3_0_0_empty_n, conv_out3_0_1_empty_n, conv_out3_0_2_empty_n, conv_out3_0_3_empty_n, conv_out3_0_4_empty_n, conv_out3_0_5_empty_n, conv_out3_0_6_empty_n, conv_out3_1_0_empty_n, conv_out3_1_1_empty_n, conv_out3_1_2_empty_n, conv_out3_1_3_empty_n, conv_out3_1_4_empty_n, conv_out3_1_5_empty_n, conv_out3_1_6_empty_n, conv_out4_0_0_empty_n, conv_out4_0_1_empty_n, conv_out4_0_2_empty_n, conv_out4_0_3_empty_n, conv_out4_0_4_empty_n, conv_out4_0_5_empty_n, conv_out4_1_0_empty_n, conv_out4_1_1_empty_n, conv_out4_1_2_empty_n, conv_out4_1_3_empty_n, conv_out4_1_4_empty_n, conv_out4_1_5_empty_n, conv_out5_0_0_empty_n, conv_out5_0_1_empty_n, conv_out5_0_2_empty_n, conv_out5_0_3_empty_n, conv_out5_0_4_empty_n, conv_out5_1_0_empty_n, conv_out5_1_1_empty_n, conv_out5_1_2_empty_n, conv_out5_1_3_empty_n, conv_out5_1_4_empty_n, feature2_embedding_full_n)
    begin
                ap_block_state1 <= ((conv_out3_1_3_empty_n = ap_const_logic_0) or (conv_out3_1_2_empty_n = ap_const_logic_0) or (conv_out3_1_1_empty_n = ap_const_logic_0) or (conv_out3_1_0_empty_n = ap_const_logic_0) or (real_start = ap_const_logic_0) or (conv_out3_0_6_empty_n = ap_const_logic_0) or (conv_out3_0_5_empty_n = ap_const_logic_0) or (conv_out3_0_4_empty_n = ap_const_logic_0) or (conv_out3_0_3_empty_n = ap_const_logic_0) or (conv_out3_0_2_empty_n = ap_const_logic_0) or (conv_out3_0_1_empty_n = ap_const_logic_0) or (conv_out3_0_0_empty_n = ap_const_logic_0) or (feature2_embedding_full_n = ap_const_logic_0) or (conv_out5_1_4_empty_n = ap_const_logic_0) or (conv_out5_1_3_empty_n = ap_const_logic_0) or (conv_out5_1_2_empty_n = ap_const_logic_0) or (conv_out5_1_1_empty_n = ap_const_logic_0) or (conv_out5_1_0_empty_n = ap_const_logic_0) or (conv_out5_0_4_empty_n = ap_const_logic_0) or (conv_out5_0_3_empty_n = ap_const_logic_0) or (conv_out5_0_2_empty_n = ap_const_logic_0) or (conv_out5_0_1_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) 
    or (conv_out5_0_0_empty_n = ap_const_logic_0) or (conv_out4_1_5_empty_n = ap_const_logic_0) or (conv_out4_1_4_empty_n = ap_const_logic_0) or (conv_out4_1_3_empty_n = ap_const_logic_0) or (conv_out4_1_2_empty_n = ap_const_logic_0) or (conv_out4_1_1_empty_n = ap_const_logic_0) or (conv_out4_1_0_empty_n = ap_const_logic_0) or (conv_out4_0_5_empty_n = ap_const_logic_0) or (conv_out4_0_4_empty_n = ap_const_logic_0) or (conv_out4_0_3_empty_n = ap_const_logic_0) or (conv_out4_0_2_empty_n = ap_const_logic_0) or (conv_out4_0_1_empty_n = ap_const_logic_0) or (conv_out4_0_0_empty_n = ap_const_logic_0) or (conv_out3_1_6_empty_n = ap_const_logic_0) or (conv_out3_1_5_empty_n = ap_const_logic_0) or (conv_out3_1_4_empty_n = ap_const_logic_0));
    end process;


    ap_done_assign_proc : process(ap_done_reg, ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(real_start, ap_CS_fsm_state1)
    begin
        if (((real_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;

    ap_ready <= internal_ap_ready;

    conv_out3_0_0_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, conv_out3_0_0_empty_n)
    begin
        if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            conv_out3_0_0_blk_n <= conv_out3_0_0_empty_n;
        else 
            conv_out3_0_0_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    conv_out3_0_0_read_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            conv_out3_0_0_read <= ap_const_logic_1;
        else 
            conv_out3_0_0_read <= ap_const_logic_0;
        end if; 
    end process;


    conv_out3_0_1_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, conv_out3_0_1_empty_n)
    begin
        if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            conv_out3_0_1_blk_n <= conv_out3_0_1_empty_n;
        else 
            conv_out3_0_1_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    conv_out3_0_1_read_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            conv_out3_0_1_read <= ap_const_logic_1;
        else 
            conv_out3_0_1_read <= ap_const_logic_0;
        end if; 
    end process;


    conv_out3_0_2_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, conv_out3_0_2_empty_n)
    begin
        if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            conv_out3_0_2_blk_n <= conv_out3_0_2_empty_n;
        else 
            conv_out3_0_2_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    conv_out3_0_2_read_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            conv_out3_0_2_read <= ap_const_logic_1;
        else 
            conv_out3_0_2_read <= ap_const_logic_0;
        end if; 
    end process;


    conv_out3_0_3_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, conv_out3_0_3_empty_n)
    begin
        if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            conv_out3_0_3_blk_n <= conv_out3_0_3_empty_n;
        else 
            conv_out3_0_3_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    conv_out3_0_3_read_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            conv_out3_0_3_read <= ap_const_logic_1;
        else 
            conv_out3_0_3_read <= ap_const_logic_0;
        end if; 
    end process;


    conv_out3_0_4_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, conv_out3_0_4_empty_n)
    begin
        if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            conv_out3_0_4_blk_n <= conv_out3_0_4_empty_n;
        else 
            conv_out3_0_4_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    conv_out3_0_4_read_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            conv_out3_0_4_read <= ap_const_logic_1;
        else 
            conv_out3_0_4_read <= ap_const_logic_0;
        end if; 
    end process;


    conv_out3_0_5_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, conv_out3_0_5_empty_n)
    begin
        if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            conv_out3_0_5_blk_n <= conv_out3_0_5_empty_n;
        else 
            conv_out3_0_5_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    conv_out3_0_5_read_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            conv_out3_0_5_read <= ap_const_logic_1;
        else 
            conv_out3_0_5_read <= ap_const_logic_0;
        end if; 
    end process;


    conv_out3_0_6_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, conv_out3_0_6_empty_n)
    begin
        if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            conv_out3_0_6_blk_n <= conv_out3_0_6_empty_n;
        else 
            conv_out3_0_6_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    conv_out3_0_6_read_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            conv_out3_0_6_read <= ap_const_logic_1;
        else 
            conv_out3_0_6_read <= ap_const_logic_0;
        end if; 
    end process;


    conv_out3_1_0_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, conv_out3_1_0_empty_n)
    begin
        if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            conv_out3_1_0_blk_n <= conv_out3_1_0_empty_n;
        else 
            conv_out3_1_0_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    conv_out3_1_0_read_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            conv_out3_1_0_read <= ap_const_logic_1;
        else 
            conv_out3_1_0_read <= ap_const_logic_0;
        end if; 
    end process;


    conv_out3_1_1_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, conv_out3_1_1_empty_n)
    begin
        if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            conv_out3_1_1_blk_n <= conv_out3_1_1_empty_n;
        else 
            conv_out3_1_1_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    conv_out3_1_1_read_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            conv_out3_1_1_read <= ap_const_logic_1;
        else 
            conv_out3_1_1_read <= ap_const_logic_0;
        end if; 
    end process;


    conv_out3_1_2_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, conv_out3_1_2_empty_n)
    begin
        if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            conv_out3_1_2_blk_n <= conv_out3_1_2_empty_n;
        else 
            conv_out3_1_2_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    conv_out3_1_2_read_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            conv_out3_1_2_read <= ap_const_logic_1;
        else 
            conv_out3_1_2_read <= ap_const_logic_0;
        end if; 
    end process;


    conv_out3_1_3_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, conv_out3_1_3_empty_n)
    begin
        if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            conv_out3_1_3_blk_n <= conv_out3_1_3_empty_n;
        else 
            conv_out3_1_3_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    conv_out3_1_3_read_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            conv_out3_1_3_read <= ap_const_logic_1;
        else 
            conv_out3_1_3_read <= ap_const_logic_0;
        end if; 
    end process;


    conv_out3_1_4_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, conv_out3_1_4_empty_n)
    begin
        if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            conv_out3_1_4_blk_n <= conv_out3_1_4_empty_n;
        else 
            conv_out3_1_4_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    conv_out3_1_4_read_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            conv_out3_1_4_read <= ap_const_logic_1;
        else 
            conv_out3_1_4_read <= ap_const_logic_0;
        end if; 
    end process;


    conv_out3_1_5_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, conv_out3_1_5_empty_n)
    begin
        if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            conv_out3_1_5_blk_n <= conv_out3_1_5_empty_n;
        else 
            conv_out3_1_5_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    conv_out3_1_5_read_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            conv_out3_1_5_read <= ap_const_logic_1;
        else 
            conv_out3_1_5_read <= ap_const_logic_0;
        end if; 
    end process;


    conv_out3_1_6_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, conv_out3_1_6_empty_n)
    begin
        if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            conv_out3_1_6_blk_n <= conv_out3_1_6_empty_n;
        else 
            conv_out3_1_6_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    conv_out3_1_6_read_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            conv_out3_1_6_read <= ap_const_logic_1;
        else 
            conv_out3_1_6_read <= ap_const_logic_0;
        end if; 
    end process;


    conv_out4_0_0_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, conv_out4_0_0_empty_n)
    begin
        if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            conv_out4_0_0_blk_n <= conv_out4_0_0_empty_n;
        else 
            conv_out4_0_0_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    conv_out4_0_0_read_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            conv_out4_0_0_read <= ap_const_logic_1;
        else 
            conv_out4_0_0_read <= ap_const_logic_0;
        end if; 
    end process;


    conv_out4_0_1_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, conv_out4_0_1_empty_n)
    begin
        if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            conv_out4_0_1_blk_n <= conv_out4_0_1_empty_n;
        else 
            conv_out4_0_1_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    conv_out4_0_1_read_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            conv_out4_0_1_read <= ap_const_logic_1;
        else 
            conv_out4_0_1_read <= ap_const_logic_0;
        end if; 
    end process;


    conv_out4_0_2_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, conv_out4_0_2_empty_n)
    begin
        if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            conv_out4_0_2_blk_n <= conv_out4_0_2_empty_n;
        else 
            conv_out4_0_2_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    conv_out4_0_2_read_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            conv_out4_0_2_read <= ap_const_logic_1;
        else 
            conv_out4_0_2_read <= ap_const_logic_0;
        end if; 
    end process;


    conv_out4_0_3_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, conv_out4_0_3_empty_n)
    begin
        if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            conv_out4_0_3_blk_n <= conv_out4_0_3_empty_n;
        else 
            conv_out4_0_3_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    conv_out4_0_3_read_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            conv_out4_0_3_read <= ap_const_logic_1;
        else 
            conv_out4_0_3_read <= ap_const_logic_0;
        end if; 
    end process;


    conv_out4_0_4_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, conv_out4_0_4_empty_n)
    begin
        if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            conv_out4_0_4_blk_n <= conv_out4_0_4_empty_n;
        else 
            conv_out4_0_4_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    conv_out4_0_4_read_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            conv_out4_0_4_read <= ap_const_logic_1;
        else 
            conv_out4_0_4_read <= ap_const_logic_0;
        end if; 
    end process;


    conv_out4_0_5_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, conv_out4_0_5_empty_n)
    begin
        if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            conv_out4_0_5_blk_n <= conv_out4_0_5_empty_n;
        else 
            conv_out4_0_5_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    conv_out4_0_5_read_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            conv_out4_0_5_read <= ap_const_logic_1;
        else 
            conv_out4_0_5_read <= ap_const_logic_0;
        end if; 
    end process;


    conv_out4_1_0_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, conv_out4_1_0_empty_n)
    begin
        if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            conv_out4_1_0_blk_n <= conv_out4_1_0_empty_n;
        else 
            conv_out4_1_0_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    conv_out4_1_0_read_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            conv_out4_1_0_read <= ap_const_logic_1;
        else 
            conv_out4_1_0_read <= ap_const_logic_0;
        end if; 
    end process;


    conv_out4_1_1_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, conv_out4_1_1_empty_n)
    begin
        if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            conv_out4_1_1_blk_n <= conv_out4_1_1_empty_n;
        else 
            conv_out4_1_1_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    conv_out4_1_1_read_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            conv_out4_1_1_read <= ap_const_logic_1;
        else 
            conv_out4_1_1_read <= ap_const_logic_0;
        end if; 
    end process;


    conv_out4_1_2_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, conv_out4_1_2_empty_n)
    begin
        if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            conv_out4_1_2_blk_n <= conv_out4_1_2_empty_n;
        else 
            conv_out4_1_2_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    conv_out4_1_2_read_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            conv_out4_1_2_read <= ap_const_logic_1;
        else 
            conv_out4_1_2_read <= ap_const_logic_0;
        end if; 
    end process;


    conv_out4_1_3_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, conv_out4_1_3_empty_n)
    begin
        if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            conv_out4_1_3_blk_n <= conv_out4_1_3_empty_n;
        else 
            conv_out4_1_3_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    conv_out4_1_3_read_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            conv_out4_1_3_read <= ap_const_logic_1;
        else 
            conv_out4_1_3_read <= ap_const_logic_0;
        end if; 
    end process;


    conv_out4_1_4_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, conv_out4_1_4_empty_n)
    begin
        if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            conv_out4_1_4_blk_n <= conv_out4_1_4_empty_n;
        else 
            conv_out4_1_4_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    conv_out4_1_4_read_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            conv_out4_1_4_read <= ap_const_logic_1;
        else 
            conv_out4_1_4_read <= ap_const_logic_0;
        end if; 
    end process;


    conv_out4_1_5_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, conv_out4_1_5_empty_n)
    begin
        if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            conv_out4_1_5_blk_n <= conv_out4_1_5_empty_n;
        else 
            conv_out4_1_5_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    conv_out4_1_5_read_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            conv_out4_1_5_read <= ap_const_logic_1;
        else 
            conv_out4_1_5_read <= ap_const_logic_0;
        end if; 
    end process;


    conv_out5_0_0_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, conv_out5_0_0_empty_n)
    begin
        if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            conv_out5_0_0_blk_n <= conv_out5_0_0_empty_n;
        else 
            conv_out5_0_0_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    conv_out5_0_0_read_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            conv_out5_0_0_read <= ap_const_logic_1;
        else 
            conv_out5_0_0_read <= ap_const_logic_0;
        end if; 
    end process;


    conv_out5_0_1_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, conv_out5_0_1_empty_n)
    begin
        if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            conv_out5_0_1_blk_n <= conv_out5_0_1_empty_n;
        else 
            conv_out5_0_1_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    conv_out5_0_1_read_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            conv_out5_0_1_read <= ap_const_logic_1;
        else 
            conv_out5_0_1_read <= ap_const_logic_0;
        end if; 
    end process;


    conv_out5_0_2_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, conv_out5_0_2_empty_n)
    begin
        if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            conv_out5_0_2_blk_n <= conv_out5_0_2_empty_n;
        else 
            conv_out5_0_2_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    conv_out5_0_2_read_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            conv_out5_0_2_read <= ap_const_logic_1;
        else 
            conv_out5_0_2_read <= ap_const_logic_0;
        end if; 
    end process;


    conv_out5_0_3_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, conv_out5_0_3_empty_n)
    begin
        if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            conv_out5_0_3_blk_n <= conv_out5_0_3_empty_n;
        else 
            conv_out5_0_3_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    conv_out5_0_3_read_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            conv_out5_0_3_read <= ap_const_logic_1;
        else 
            conv_out5_0_3_read <= ap_const_logic_0;
        end if; 
    end process;


    conv_out5_0_4_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, conv_out5_0_4_empty_n)
    begin
        if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            conv_out5_0_4_blk_n <= conv_out5_0_4_empty_n;
        else 
            conv_out5_0_4_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    conv_out5_0_4_read_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            conv_out5_0_4_read <= ap_const_logic_1;
        else 
            conv_out5_0_4_read <= ap_const_logic_0;
        end if; 
    end process;


    conv_out5_1_0_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, conv_out5_1_0_empty_n)
    begin
        if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            conv_out5_1_0_blk_n <= conv_out5_1_0_empty_n;
        else 
            conv_out5_1_0_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    conv_out5_1_0_read_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            conv_out5_1_0_read <= ap_const_logic_1;
        else 
            conv_out5_1_0_read <= ap_const_logic_0;
        end if; 
    end process;


    conv_out5_1_1_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, conv_out5_1_1_empty_n)
    begin
        if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            conv_out5_1_1_blk_n <= conv_out5_1_1_empty_n;
        else 
            conv_out5_1_1_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    conv_out5_1_1_read_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            conv_out5_1_1_read <= ap_const_logic_1;
        else 
            conv_out5_1_1_read <= ap_const_logic_0;
        end if; 
    end process;


    conv_out5_1_2_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, conv_out5_1_2_empty_n)
    begin
        if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            conv_out5_1_2_blk_n <= conv_out5_1_2_empty_n;
        else 
            conv_out5_1_2_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    conv_out5_1_2_read_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            conv_out5_1_2_read <= ap_const_logic_1;
        else 
            conv_out5_1_2_read <= ap_const_logic_0;
        end if; 
    end process;


    conv_out5_1_3_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, conv_out5_1_3_empty_n)
    begin
        if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            conv_out5_1_3_blk_n <= conv_out5_1_3_empty_n;
        else 
            conv_out5_1_3_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    conv_out5_1_3_read_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            conv_out5_1_3_read <= ap_const_logic_1;
        else 
            conv_out5_1_3_read <= ap_const_logic_0;
        end if; 
    end process;


    conv_out5_1_4_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, conv_out5_1_4_empty_n)
    begin
        if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            conv_out5_1_4_blk_n <= conv_out5_1_4_empty_n;
        else 
            conv_out5_1_4_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    conv_out5_1_4_read_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            conv_out5_1_4_read <= ap_const_logic_1;
        else 
            conv_out5_1_4_read <= ap_const_logic_0;
        end if; 
    end process;


    feature2_embedding_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, feature2_embedding_full_n)
    begin
        if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            feature2_embedding_blk_n <= feature2_embedding_full_n;
        else 
            feature2_embedding_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    feature2_embedding_din <= (((((((((((((((((((((((((((((((((((conv_out5_1_4_dout & conv_out5_1_3_dout) & conv_out5_1_2_dout) & conv_out5_1_1_dout) & conv_out5_1_0_dout) & conv_out5_0_4_dout) & conv_out5_0_3_dout) & conv_out5_0_2_dout) & conv_out5_0_1_dout) & conv_out5_0_0_dout) & conv_out4_1_5_dout) & conv_out4_1_4_dout) & conv_out4_1_3_dout) & conv_out4_1_2_dout) & conv_out4_1_1_dout) & conv_out4_1_0_dout) & conv_out4_0_5_dout) & conv_out4_0_4_dout) & conv_out4_0_3_dout) & conv_out4_0_2_dout) & conv_out4_0_1_dout) & conv_out4_0_0_dout) & conv_out3_1_6_dout) & conv_out3_1_5_dout) & conv_out3_1_4_dout) & conv_out3_1_3_dout) & conv_out3_1_2_dout) & conv_out3_1_1_dout) & conv_out3_1_0_dout) & conv_out3_0_6_dout) & conv_out3_0_5_dout) & conv_out3_0_4_dout) & conv_out3_0_3_dout) & conv_out3_0_2_dout) & conv_out3_0_1_dout) & conv_out3_0_0_dout);

    feature2_embedding_write_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            feature2_embedding_write <= ap_const_logic_1;
        else 
            feature2_embedding_write <= ap_const_logic_0;
        end if; 
    end process;


    internal_ap_ready_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            internal_ap_ready <= ap_const_logic_1;
        else 
            internal_ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    real_start_assign_proc : process(ap_start, start_full_n, start_once_reg)
    begin
        if (((start_full_n = ap_const_logic_0) and (start_once_reg = ap_const_logic_0))) then 
            real_start <= ap_const_logic_0;
        else 
            real_start <= ap_start;
        end if; 
    end process;

    start_out <= real_start;

    start_write_assign_proc : process(real_start, start_once_reg)
    begin
        if (((real_start = ap_const_logic_1) and (start_once_reg = ap_const_logic_0))) then 
            start_write <= ap_const_logic_1;
        else 
            start_write <= ap_const_logic_0;
        end if; 
    end process;

end behav;
