# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/sidejob/kitsum_1024B_xy_20231211/kits_prj.srcs/sources_1/IP/ila_axis_1024/ila_axis_1024.xci
# IP: The module: 'ila_axis_1024' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/sidejob/kitsum_1024B_xy_20231211/kits_prj.srcs/sources_1/IP/ila_axis_1024/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_axis_1024'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/sidejob/kitsum_1024B_xy_20231211/kits_prj.srcs/sources_1/IP/ila_axis_1024/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_axis_1024'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/sidejob/kitsum_1024B_xy_20231211/kits_prj.srcs/sources_1/IP/ila_axis_1024/ila_axis_1024_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_axis_1024'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: D:/sidejob/kitsum_1024B_xy_20231211/kits_prj.srcs/sources_1/IP/ila_axis_1024/ila_axis_1024.xci
# IP: The module: 'ila_axis_1024' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/sidejob/kitsum_1024B_xy_20231211/kits_prj.srcs/sources_1/IP/ila_axis_1024/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_axis_1024'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/sidejob/kitsum_1024B_xy_20231211/kits_prj.srcs/sources_1/IP/ila_axis_1024/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_axis_1024'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/sidejob/kitsum_1024B_xy_20231211/kits_prj.srcs/sources_1/IP/ila_axis_1024/ila_axis_1024_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_axis_1024'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
