# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/sidejob/kitsum_1024B_xy_20231211/kits_prj.srcs/sources_1/IP/fifo_axis_data_indepenclk_64/fifo_axis_data_indepenclk_64.xci
# IP: The module: 'fifo_axis_data_indepenclk_64' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/sidejob/kitsum_1024B_xy_20231211/kits_prj.srcs/sources_1/IP/fifo_axis_data_indepenclk_64/fifo_axis_data_indepenclk_64_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_axis_data_indepenclk_64'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: D:/sidejob/kitsum_1024B_xy_20231211/kits_prj.srcs/sources_1/IP/fifo_axis_data_indepenclk_64/fifo_axis_data_indepenclk_64.xci
# IP: The module: 'fifo_axis_data_indepenclk_64' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/sidejob/kitsum_1024B_xy_20231211/kits_prj.srcs/sources_1/IP/fifo_axis_data_indepenclk_64/fifo_axis_data_indepenclk_64_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_axis_data_indepenclk_64'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
